apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: Secret for consumer module
    iconClass: icon-quarkus
    openshift.io/display-name: Consumer Module secrets
    openshift.io/long-description: This template deploys Secret for Consumer module
    tags: ride-consumer-module
  name: ride-consumer-module-secret-template
  namespace: ${NAMESPACE}
labels:
  app.kubernetes.io/component: consumer-module
  app.kubernetes.io/name: ride
  app.kubernetes.io/managed-by: template
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      namespace: ${NAMESPACE}
      labels:
        app: ${NAME}-${COMPONENT}-${VERSION}
      name: ${NAME}-${COMPONENT}-${VERSION}
    stringData:
      APP_ACCEPTED_EVENT_TOPIC: ${APP_ACCEPTED_EVENT_TOPIC}
      DISCLOSURE_EVENT_TOPIC: ${DISCLOSURE_EVENT_TOPIC}
      EVSUBMITTED_EVENT_TOPIC: ${EVSUBMITTED_EVENT_TOPIC}
      IMAGE_NAMESPACE: ${IMAGE_NAMESPACE}
      IMAGE_REGISTRY: ${IMAGE_REGISTRY}
      KAFKA_SASL_CONFIG: ${KAFKA_SASL_CONFIG}
      KAFKA_SASL_MECH: ${KAFKA_SASL_MECH}
      KAFKA_SCHEMA_REGISTRY: ${KAFKA_SCHEMA_REGISTRY}
      KAFKA_SEC_PROTOCOL: ${KAFKA_SEC_PROTOCOL}
      KAFKA_SERVER: ${KAFKA_SERVER}
      PAYRECVD_EVENT_TOPIC: ${PAYRECVD_EVENT_TOPIC}
      REVSCHED_EVENT_TOPIC: ${REVSCHED_EVENT_TOPIC}
      SSL_PROTOCOL: ${SSL_PROTOCOL}
      SSL_TRUSTSTORE: ${SSL_TRUSTSTORE}
      SSL_TRUSTTORE_PASS: ${SSL_TRUSTTORE_PASS}
      SSL_TRUSTTORE_TYPE: ${SSL_TRUSTTORE_TYPE}
      TEST_EVENT_TOPIC: ${TEST_EVENT_TOPIC}
      APP_ACCEPTED_EVENT_DECODED_TOPIC: ${APP_ACCEPTED_EVENT_DECODED_TOPIC}
      DISCLOSURE_EVENT_DECODED_TOPIC: ${DISCLOSURE_EVENT_DECODED_TOPIC}
      EVSUBMITTED_EVENT_DECODED_TOPIC: ${EVSUBMITTED_EVENT_DECODED_TOPIC}
      PAYRECVD_EVENT_DECODED_TOPIC: ${PAYRECVD_EVENT_DECODED_TOPIC}
      REVSCHED_EVENT_DECODED_TOPIC: ${REVSCHED_EVENT_DECODED_TOPIC}
      TEST_EVENT_SINK_TOPIC: ${TEST_EVENT_SINK_TOPIC}
      KAFKA_CONFLUENT_COMPAT_REGISTRY: ${KAFKA_CONFLUENT_COMPAT_REGISTRY}
    type: Opaque
parameters:
  - description: The name of the application for labelling all artifacts.
    displayName: Application Name
    name: NAME
    value: ride
  - name: COMPONENT
    value: consumer-module-build-secret
  - name: VERSION
    value: pr
  - name: NAMESPACE
  - name: APP_ACCEPTED_EVENT_TOPIC
  - name: DISCLOSURE_EVENT_TOPIC
  - name: EVSUBMITTED_EVENT_TOPIC
  - name: IMAGE_NAMESPACE
  - name: IMAGE_REGISTRY
  - name: KAFKA_SASL_CONFIG
  - name: KAFKA_SASL_MECH
  - name: KAFKA_SCHEMA_REGISTRY
  - name: KAFKA_SEC_PROTOCOL
  - name: KAFKA_SERVER
  - name: PAYRECVD_EVENT_TOPIC
  - name: REVSCHED_EVENT_TOPIC
  - name: SSL_PROTOCOL
  - name: SSL_TRUSTSTORE
  - name: SSL_TRUSTTORE_PASS
  - name: SSL_TRUSTTORE_TYPE
  - name: TEST_EVENT_TOPIC
  - name: APP_ACCEPTED_EVENT_DECODED_TOPIC
  - name: DISCLOSURE_EVENT_DECODED_TOPIC
  - name: EVSUBMITTED_EVENT_DECODED_TOPIC
  - name: PAYRECVD_EVENT_DECODED_TOPIC
  - name: REVSCHED_EVENT_DECODED_TOPIC
  - name: TEST_EVENT_SINK_TOPIC
  - name: KAFKA_CONFLUENT_COMPAT_REGISTRY