apiVersion: tekton.dev/v1beta1 
kind: Task 
metadata: 
  name: t-ride-cleanup-workspace 
spec:
  workspaces:
    - name: source
      description: A workspace to be cleaned.
  steps: 
    - name: remove-source 
      image: registry.access.redhat.com/ubi8/ubi
      command: 
        - /bin/bash
      args:
        - "-c"
        - "rm -rf $(workspaces.source.path)/source"
    - name: message
      image: registry.access.redhat.com/ubi8/ubi
      command:
        - /bin/bash 
      args:
        - "-c"
        - "echo All files were deleted" 