---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/commit-id: a9637ef49f79a01e93067df03578e9fe3519126d
    app.quarkus.io/build-timestamp: 2022-11-16 - 20:57:50 +0000
  labels:
    app.kubernetes.io/name: testquarkus
    app.kubernetes.io/version: "1.0"
  name: testquarkus
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: testquarkus
    app.kubernetes.io/version: "1.0"
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/commit-id: a9637ef49f79a01e93067df03578e9fe3519126d
    app.quarkus.io/build-timestamp: 2022-11-16 - 20:57:50 +0000
  labels:
    app.kubernetes.io/name: testquarkus
    app.kubernetes.io/version: "1.0"
  name: testquarkus
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: testquarkus
      app.kubernetes.io/version: "1.0"
  template:
    metadata:
      annotations:
        app.quarkus.io/commit-id: a9637ef49f79a01e93067df03578e9fe3519126d
        app.quarkus.io/build-timestamp: 2022-11-16 - 20:57:50 +0000
      labels:
        app.kubernetes.io/name: testquarkus
        app.kubernetes.io/version: "1.0"
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: image-registry.openshift-image-registry.svc:5000/be5301-tools/ride-producer-api-image:1.0
          imagePullPolicy: Always
          name: testquarkus
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
