apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: Secret for recon api
    iconClass: icon-python
    openshift.io/display-name: recon API secrets
    openshift.io/long-description: This template deploys Secret for recon API
    tags: ride-recon
  name: ride-recon-api-secret-template
  # namespace: ${NAMESPACE}
labels:
  app.kubernetes.io/component: recon-api
  app.kubernetes.io/name: ride
  app.kubernetes.io/managed-by: template
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      # namespace: ${NAMESPACE}
      # labels:
      #   app: ${NAME}-${COMPONENT}-${VERSION}
      name: ${NAME}-${COMPONENT}-${VERSION}
    stringData:
      ERR_STG_COLLECTION: ${ERR_STG_COLLECTION}
      ERR_THRESHOLD_COUNT: ${ERR_THRESHOLD_COUNT}
      LOG_LEVEL: ${LOG_LEVEL}
      MAIN_STG_COLLECTION: ${MAIN_STG_COLLECTION}
      MAIN_TABLE_COLLECTION: ${MAIN_TABLE_COLLECTION}
      MONGO_URL: ${MONGO_URL}
      RECON_DB_NAME: ${RECON_DB_NAME}
      ERR_TABLE_COLLECTION: ${ERR_TABLE_COLLECTION}
    type: Opaque
parameters:
  - description: The name of the application for labelling all artifacts.
    displayName: Application Name
    name: NAME
    value: recon-api
  - name: COMPONENT
    value: recon-api-build-secret
  - name: VERSION
    value: dev
  - name: NAMESPACE
  - name: ERR_STG_COLLECTION
    value: errorstaging
  - name: ERR_THRESHOLD_COUNT
    value: "2"
  - name: LOG_LEVEL
    value: DEBUG
  - name: MAIN_STG_COLLECTION
    value: mainstaging
  - name: MAIN_TABLE_COLLECTION
    value: maintable
  - name: MONGO_URL
    value:
  - name: RECON_DB_NAME
    value: kafkaevents
  - name: ERR_TABLE_COLLECTION
    value: errortable