kind: Template
apiVersion: template.openshift.io/v1
metadata:
  annotations:
    description: Build template for ride producer api
    tags: rsbc-ride-producer-api
    iconClass: icon-quarkus
  name: ${NAME}-${COMPONENT}-build-template
objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: ${NAME}-${COMPONENT}-image
      labels:
        shared: "true"
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: ${NAME}-${COMPONENT}-${BUILD_CONFIG_SUFFIX}
      labels:
        app: ${NAME}-${COMPONENT}
        component: ${NAME}-${COMPONENT}-${BUILD_CONFIG_SUFFIX}
        name: ${NAME}-${COMPONENT}-${BUILD_CONFIG_SUFFIX}
    spec:
      source:
        type: Git
        contextDir: ${SOURCE_CONTEXT_DIR}
        git:
          uri: ${SOURCE_REPOSITORY_URL}
          ref: ${SOURCE_REPOSITORY_REF}
      completionDeadlineSeconds: 1440
      resources:
        limits:
          cpu: 1
          memory: 4Gi
        requests:
          cpu: 1
          memory: 4Gi
      strategy:
        type: Docker
        dockerStrategy:
          dockerfilePath: Dockerfile.native.multistage
      output:
        to:
          kind: ImageStreamTag
          name: ${NAME}-${COMPONENT}-image:${VERSION}
      # triggers:
      #   - type: ConfigChange
parameters:
  - name: NAME
    displayName: Name
    description: The name assigned to all of the objects defined in this template.  You should keep this as default unless your know what your doing.
    required: true
    # value: ride
  - name: VERSION
    displayName: Application version number
    description: Application version number
    required: true
    # value: "1.1"
  - name: SOURCE_CONTEXT_DIR
    displayName: Source Directory
    description: directory
    required: true
    value: "rsbc-ride-producer-api/"
  - name: SOURCE_REPOSITORY_URL
    displayName: Git Repo URL
    description: The URL to your GIT repo, don't use the this default unless your just experimenting.
    required: true
    value: "https://github.com/bcgov/jag-rsbc-ride"
  - name: SOURCE_REPOSITORY_REF
    displayName: Git Reference
    description: The git reference or branch.
    required: true
  - name: BUILD_CONFIG_SUFFIX
    displayName: Build Config Suffix
    required: true
    description: Suffix_for_buildconfig
    value: pr
  - name: COMPONENT
    value: producer-api