apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ride-build-and-deploy-temp-2
spec:
  workspaces:
  - name: shared-workspace
  params:
  - name: deployment-name
    type: string
    description: name of the deployment to be patched
  - name: git-url
    type: string
    description: url of the git repo for the code of deployment
  - name: git-revision
    type: string
    description: revision to be used from repo of the code for deployment
    default: "master"
  - name: IMAGE-MOCKPRODUCER
    type: string
    description: image for mockproducer to be build from the code
  - name: DOCKERFILE-MOCKPRODUCER
    type: string
    description: Path to the Dockerfile to build mockproducer
  - name: CONTEXT-MOCKPRODUCER
    type: string
    description: Path to the mockproducer directory to use as context
  - name: IMAGE-MOCKCONSUMER
    type: string
    description: image of mockconsumer to be build from the code
  - name: DOCKERFILE-MOCKCONSUMER
    type: string
    description: Path to the Dockerfile to build mockconsumer
  - name: CONTEXT-MOCKCONSUMER
    type: string
    description: Path to the mockconsumer directory to use as context
  - name: IMAGE_REGISTRY
    type: string
    description: The Root url of the image registry.
    default: docker.io
  tasks:
  - name: fetch-repository
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    - name: output
      workspace: shared-workspace
    params:
    - name: url
      value: $(params.git-url)
    - name: subdirectory
      value: ""
    - name: deleteExisting
      value: "true"
    - name: revision
      value: $(params.git-revision)
  - name: generate-id
    runAfter:
    - fetch-repository
    taskRef:
      kind: Task
      name: t-generate-id
    workspaces:
    - name: source
      workspace: shared-workspace
  - name: build-image-for-mockproducer
    taskRef:
      name: t-buildah-with-resource-setting
    params:
    - name: IMAGE
      value: $(params.IMAGE-MOCKPRODUCER)
    - name: IMAGE_TAG
      value: $(tasks.generate-id.results.short-commit)
    - name: DOCKERFILE
      value: $(params.DOCKERFILE-MOCKPRODUCER)
    - name: CONTEXT
      value: $(params.CONTEXT-MOCKPRODUCER)
    - name: IMAGE_REGISTRY
      value: $(params.IMAGE_REGISTRY)
    workspaces:
    - name: source
      workspace: shared-workspace
    runAfter:
    - generate-id
  - name: build-image-for-mockconsumer
    taskRef:
      name: t-buildah-with-resource-setting
    params:
    - name: IMAGE
      value: $(params.IMAGE-MOCKCONSUMER)
    - name: IMAGE_TAG
      value: $(tasks.generate-id.results.short-commit)
    - name: DOCKERFILE
      value: $(params.DOCKERFILE-MOCKCONSUMER)
    - name: CONTEXT
      value: $(params.CONTEXT-MOCKCONSUMER)
    - name: IMAGE_REGISTRY
      value: $(params.IMAGE_REGISTRY)
    workspaces:
    - name: source
      workspace: shared-workspace
    runAfter:
    - generate-id