apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: ride-open-pr
spec:
  pipelineSpec:
    tasks:
      - name: test-open-pr
        taskRef:
          name: t-github-open-pr
        params:
        - name: GITHUB_HOST_URL
          value: "api.github.com"
        - name: REPO_FULL_NAME
          value: "bcgov-c/tenant-gitops-be5301"
        - name: GITHUB_TOKEN_SECRET_NAME
          value: "argocd-repo-github-pat-token"
        - name: GITHUB_TOKEN_SECRET_KEY
          value: "password"
        - name: HEAD
          value: "jag-rsbc-ride"
        - name: BASE
          value: "feature/update-argoCD-application-yaml"
        - name: TITLE
          value: "title"
        - name: BODY
          value: "body"