apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ride-build-update-image-use-github-cli
spec:
  workspaces:
  - name: shared-workspace
  - name: input
  params:
  - name: git-url-destination
    type: string
    description: url of the git repo for the code of deployment
  - name: git-revision-destination
    type: string
    description: revision to be used from repo of the code for deployment
    default: "pr"
  - name: subdirectory-destination
    type: string
    description: sub directory
    default: ""
  - name: pr-number
    type: string
    description: the PR number
    default: ""
  - name: GIT_USER_NAME_DESTINATION
    type: string
    description: git user name
    default: ""
  - name: GIT_USER_EMAIL_DESTINATION
    type: string
    description: git user email
    default: ""

  tasks:
  - name: fetch-gitops-repo-as-input
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    - name: output
      workspace: input
    params:
    - name: url
      value: $(params.git-url-destination)
    - name: subdirectory
      value: $(params.subdirectory-destination)
    - name: deleteExisting
      value: "true"
    - name: revision
      value: $(params.git-revision-destination)   
  - name: yq-replace-image-tag
    taskRef:
      name: t-ride-yq-03
    workspaces:
    - name: source
      workspace: input
    params:
    - name: git-revision-destination
      value: $(params.git-revision-destination)
    - name: pr-number
      value: $(params.pr-number)
    runAfter:
    - fetch-gitops-repo-as-input
  - name: fetch-gitops-repo-as-source-and-update
    taskRef:
      name: t-ride-git-cli
    workspaces:
    - name: source
      workspace: shared-workspace
    - name: input
      workspace: input
    params:
    - name: git-url-destination
      value: $(params.git-url-destination)
    - name: git-revision-destination
      value: $(params.git-revision-destination)
    - name: GIT_USER_NAME
      value: $(params.GIT_USER_NAME_DESTINATION)
    - name: GIT_USER_EMAIL
      value: $(params.GIT_USER_EMAIL_DESTINATION)
    runAfter:
    - fetch-gitops-repo-as-input
  - name: create-pr-to-master-branch
    taskRef:
      name: t-github-open-pr
    params:
      - name: GITHUB_HOST_URL
        value: "https://github.com/"
      - name: REPO_FULL_NAME
        value: "bcgov-c/tenant-gitops-be5301"
      - name: HEAD
        value: $(params.git-revision-destination)
      - name: BASE
        value: main
      - name: TITLE
        value: $(params.pr-number)
      - name: BODY
        value: "The PR includes the following changes: RIDE components deployment manifest to pr, dev, test and prod environment"
    runAfter:
    - fetch-gitops-repo-as-source-and-update