apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ride-build-and-deploy
spec:
  workspaces:
  - name: shared-workspace
  - name: input
  - name: source
  params:
  - name: git-url-source
    type: string
    description: url of the git repo for the source code for build
  - name: git-revision-source
    type: string
    description: revision to be used from repo of the source code for build
    default: "master"
  - name: IMAGE-MOCKPRODUCER
    type: string
    description: image for mockproducer to be build from the code
  - name: DOCKERFILE-MOCKPRODUCER
    type: string
    description: Path to the Dockerfile to build mockproducer
  - name: CONTEXT-MOCKPRODUCER
    type: string
    description: Path to the mockproducer directory to use as context
  - name: IMAGE-MOCKCONSUMER
    type: string
    description: image of mockconsumer to be build from the code
  - name: DOCKERFILE-MOCKCONSUMER
    type: string
    description: Path to the Dockerfile to build mockconsumer
  - name: CONTEXT-MOCKCONSUMER
    type: string
    description: Path to the mockconsumer directory to use as context
  - name: IMAGE_REGISTRY
    type: string
    description: The Root url of the image registry.
    default: docker.io

  - name: git-url-destination
    type: string
    description: url of the git repo for the code of deployment
  - name: git-revision-destination
    type: string
    description: revision to be used from repo of the code for deployment
    default: "jag-rsbc-ride"
  - name: subdirectory-destination
    type: string
    description: sub directory
    default: ""
  - name: pr-number
    type: string
    description: the PR number
    default: ""
  - name: GIT_USER_NAME_DESTINATION
    type: string
    description: git user name
    default: ""
  - name: GIT_USER_EMAIL_DESTINATION
    type: string
    description: git user email
    default: ""
  - name: pr-destination
    description: pr destination branch
    type: string
    default: ""
  - name: git-commit-comments
    description: git commit comments
    type: string
    default: ""

  - name: GITHUB_HOST_URL
    description: The GitHub host, adjust this if you run a GitHub enteprise.
    type: string
    default: "api.github.com"
  - name: REPO_FULL_NAME
    description: The GitHub repository full name, e.g. - tektoncd/catalog
    type: string
    default: "bcgov-c/tenant-gitops-be5301"
  - name: GITHUB_TOKEN_SECRET_NAME
    description: The name of the kubernetes secret that contains the GitHub token, default - github
    type: string
    default: "argocd-repo-github-pat-token"
  - name: GITHUB_TOKEN_SECRET_KEY
    description: The key within the kubernetes secret that contains the GitHub token, default - token
    type: string
    default: "password"
  - name: HEAD
    description: The name of the branch where your changes are implemented.
    type: string
    default: "jag-rsbc-ride"
  - name: BASE
    description: The name of the branch you want the changes pulled into.
    type: string
    default: "main"
  - name: BODY
    description: The body description of the pull request.
    type: string
    default: "This pull request includes the following changes: RIDE components deployment manifest to pr, dev, test and prod environment;"
  - name: TITLE
    description: The title of the pull request.
    type: string
    default: "Deployment manifest"
    
  tasks:
  - name: fetch-ride-repo-to-build
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    - name: output
      workspace: shared-workspace
    params:
    - name: url
      value: $(params.git-url-source)
    - name: subdirectory
      value: ""
    - name: deleteExisting
      value: "true"
    - name: revision
      value: $(params.git-revision-source)
  - name: build-image-for-mockproducer
    taskRef:
      name: t-buildah-with-resource-setting
    params:
    - name: IMAGE
      value: $(params.IMAGE-MOCKPRODUCER)
    - name: IMAGE_TAG
      value: $(params.pr-number)
    - name: DOCKERFILE
      value: $(params.DOCKERFILE-MOCKPRODUCER)
    - name: CONTEXT
      value: $(params.CONTEXT-MOCKPRODUCER)
    - name: IMAGE_REGISTRY
      value: $(params.IMAGE_REGISTRY)
    workspaces:
    - name: source
      workspace: shared-workspace
    runAfter:
    - fetch-ride-repo-to-build
  - name: build-image-for-mockconsumer
    taskRef:
      name: t-buildah-with-resource-setting
    params:
    - name: IMAGE
      value: $(params.IMAGE-MOCKCONSUMER)
    - name: IMAGE_TAG
      value: $(params.pr-number)
    - name: DOCKERFILE
      value: $(params.DOCKERFILE-MOCKCONSUMER)
    - name: CONTEXT
      value: $(params.CONTEXT-MOCKCONSUMER)
    - name: IMAGE_REGISTRY
      value: $(params.IMAGE_REGISTRY)
    workspaces:
    - name: source
      workspace: shared-workspace
    runAfter:
    - fetch-ride-repo-to-build
  - name: fetch-gitops-repo-as-input
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    - name: output
      workspace: input
    params:
    - name: url
      value: $(params.git-url-destination)
    - name: subdirectory
      value: $(params.subdirectory-destination)
    - name: deleteExisting
      value: "true"
    - name: revision
      value: $(params.git-revision-destination) 
    runAfter:
    - build-image-for-mockconsumer
    - build-image-for-mockproducer
  - name: yq-replace-image-tag
    taskRef:
      name: t-ride-yq-03
    workspaces:
    - name: source
      workspace: input
    params:
    - name: pr-number
      value: $(params.pr-number)
    - name: pr-destination
      value: $(params.pr-destination)
    runAfter:
    - fetch-gitops-repo-as-input
  - name: fetch-gitops-repo-as-source-and-update
    taskRef:
      name: t-ride-git-cli
    workspaces:
    - name: source
      workspace: source
    - name: input
      workspace: input
    params:
    - name: git-url-destination
      value: $(params.git-url-destination)
    - name: git-revision-destination
      value: $(params.git-revision-destination)
    - name: GIT_USER_NAME
      value: $(params.GIT_USER_NAME_DESTINATION)
    - name: GIT_USER_EMAIL
      value: $(params.GIT_USER_EMAIL_DESTINATION)
    - name: git-commit-comments
      value: $(params.git-commit-comments)
    - name: pr-destination
      value: $(params.pr-destination)
    runAfter:
    - yq-replace-image-tag
  - name: create-pr-to-master-branch
    taskRef:
      name: t-github-open-pr
    params:
      - name: GITHUB_HOST_URL
        value: $(params.GITHUB_HOST_URL)
      - name: REPO_FULL_NAME
        value: $(params.REPO_FULL_NAME)
      - name: HEAD
        value: $(params.HEAD)
      - name: BASE
        value: $(params.BASE)
      - name: TITLE
        value: $(params.TITLE)
      - name: BODY
        value: $(params.BODY)
    runAfter:
    - fetch-gitops-repo-as-source-and-update