apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ride-build-and-deploy
spec:
  workspaces:
  - name: shared-workspace
  params:
  - name: git-url
    type: string
    description: url of the git repo for the source code for build
  - name: git-revision
    type: string
    description: revision to be used from repo of the source code for build
    default: "master"
  - name: git-url-destination
    type: string
    description: url of the git repo for the code of deployment
  - name: git-revision-destination
    type: string
    description: revision to be used from repo of the code for deployment
    default: "main"
  - name: IMAGE-MOCKPRODUCER
    type: string
    description: image for mockproducer to be build from the code
  - name: DOCKERFILE-MOCKPRODUCER
    type: string
    description: Path to the Dockerfile to build mockproducer
  - name: CONTEXT-MOCKPRODUCER
    type: string
    description: Path to the mockproducer directory to use as context
  - name: IMAGE-MOCKCONSUMER
    type: string
    description: image of mockconsumer to be build from the code
  - name: DOCKERFILE-MOCKCONSUMER
    type: string
    description: Path to the Dockerfile to build mockconsumer
  - name: CONTEXT-MOCKCONSUMER
    type: string
    description: Path to the mockconsumer directory to use as context
  - name: IMAGE_REGISTRY
    type: string
    description: The Root url of the image registry.
    default: docker.io
  tasks:
  - name: fetch-repository
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    - name: output
      workspace: shared-workspace
    params:
    - name: url
      value: $(params.git-url)
    - name: subdirectory
      value: ""
    - name: deleteExisting
      value: "true"
    - name: revision
      value: $(params.git-revision)
  - name: generate-id
    runAfter:
    - fetch-repository
    taskRef:
      kind: Task
      name: t-generate-id
    workspaces:
    - name: source
      workspace: shared-workspace
  - name: build-image-for-mockproducer
    taskRef:
      name: t-buildah-with-resource-setting
    params:
    - name: IMAGE
      value: $(params.IMAGE-MOCKPRODUCER)
    - name: IMAGE_TAG
      value: $(tasks.generate-id.results.short-commit)
    - name: DOCKERFILE
      value: $(params.DOCKERFILE-MOCKPRODUCER)
    - name: CONTEXT
      value: $(params.CONTEXT-MOCKPRODUCER)
    - name: IMAGE_REGISTRY
      value: $(params.IMAGE_REGISTRY)
    workspaces:
    - name: source
      workspace: shared-workspace
    runAfter:
    - generate-id
  - name: build-image-for-mockconsumer
    taskRef:
      name: t-buildah-with-resource-setting
    params:
    - name: IMAGE
      value: $(params.IMAGE-MOCKCONSUMER)
    - name: IMAGE_TAG
      value: $(tasks.generate-id.results.short-commit)
    - name: DOCKERFILE
      value: $(params.DOCKERFILE-MOCKCONSUMER)
    - name: CONTEXT
      value: $(params.CONTEXT-MOCKCONSUMER)
    - name: IMAGE_REGISTRY
      value: $(params.IMAGE_REGISTRY)
    workspaces:
    - name: source
      workspace: shared-workspace
    runAfter:
    - generate-id
  - name: fetch-destination-repository
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    - name: output
      workspace: shared-workspace
    params:
    - name: url
      value: $(params.git-url-destination)
    - name: subdirectory
      value: "deployment/jag-rsbc-ride"
    - name: deleteExisting
      value: "true"
    - name: revision
      value: $(params.git-revision-destination)
    runAfter:
    - build-image-for-mockproducer
    - build-image-for-mockconsumer
  - name: yq-replace
    taskRef:
      name: t-yq
    workspaces:
    - name: output
      workspace: shared-workspace
    params:
      - name: files
        value:
        - "./overlays/pr/kustomization-template.yaml"
        - "./overlays/pr/custom-service-referenced-by-mockproducer-route.yaml"
        - "./overlays/pr/custom-mockconsumer-env.yaml"
        - "./overlays/pr/custom-servicename-kafka.yaml"
        - "./overlays/pr/custom-servicename-kafka-zookeeper.yaml"
        - "./overlays/pr/custom-mockproducer-pod-selector.yaml"
        - "./overlays/pr/custom-mockproducer-service-pod-selector.yaml"
        - "./overlays/pr/custom-mockconsumer-pod-selector.yaml"
        - "./overlays/pr/custom-mockconsumer-service-pod-selector.yaml"
        - "./overlays/pr/custom-kafka-pod-selector.yaml"
        - "./overlays/pr/custom-kafka-service-pod-selector.yaml"
        - "./overlays/pr/custom-kafka-zookeeper-pod-selector.yaml"
        - "./overlays/pr/custom-kafka-zookeeper-service-pod-selector.yaml"
      - name: expression
        value: .image="$(params.new-image-sha)"
    runAfter:
    - fetch-destination-repository