apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ride-build-update-image-final
spec:
  workspaces:
  - name: shared-workspace
  - name: input
  - name: source
  params:
  - name: git-url-source
    type: string
    description: url of the git repo for the source code for build
  - name: git-revision-source
    type: string
    description: revision to be used from repo of the source code for build
    default: "master"
  - name: IMAGE-MOCKPRODUCER
    type: string
    description: image for mockproducer to be build from the code
  - name: DOCKERFILE-MOCKPRODUCER
    type: string
    description: Path to the Dockerfile to build mockproducer
  - name: CONTEXT-MOCKPRODUCER
    type: string
    description: Path to the mockproducer directory to use as context
  - name: IMAGE-MOCKCONSUMER
    type: string
    description: image of mockconsumer to be build from the code
  - name: DOCKERFILE-MOCKCONSUMER
    type: string
    description: Path to the Dockerfile to build mockconsumer
  - name: CONTEXT-MOCKCONSUMER
    type: string
    description: Path to the mockconsumer directory to use as context
  - name: IMAGE_REGISTRY
    type: string
    description: The Root url of the image registry.
    default: docker.io

  - name: git-url-destination
    type: string
    description: url of the git repo for the code of deployment
  - name: git-revision-destination
    type: string
    description: revision to be used from repo of the code for deployment
    default: "pr"
  - name: subdirectory-destination
    type: string
    description: sub directory
    default: ""
  - name: pr-number
    type: string
    description: the PR number
    default: ""
  - name: yq-command
    type: string
    description: yq command
    default: |

  - name: GIT_SCRIPT
    type: string
    description: git scripts
    default: |

  tasks:
  - name: fetch-ride-repo-to-build
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    - name: output
      workspace: shared-workspace
    params:
    - name: url
      value: $(params.git-url-source)
    - name: subdirectory
      value: ""
    - name: deleteExisting
      value: "true"
    - name: revision
      value: $(params.git-revision-source)
  - name: generate-id
    runAfter:
    - fetch-ride-repo-to-build
    taskRef:
      kind: Task
      name: t-generate-id
    workspaces:
    - name: source
      workspace: shared-workspace
  - name: build-image-for-mockproducer
    taskRef:
      name: t-buildah-with-resource-setting
    params:
    - name: IMAGE
      value: $(params.IMAGE-MOCKPRODUCER)
    - name: IMAGE_TAG
      value: $(params.pr-number)
    - name: DOCKERFILE
      value: $(params.DOCKERFILE-MOCKPRODUCER)
    - name: CONTEXT
      value: $(params.CONTEXT-MOCKPRODUCER)
    - name: IMAGE_REGISTRY
      value: $(params.IMAGE_REGISTRY)
    workspaces:
    - name: source
      workspace: shared-workspace
    runAfter:
    - generate-id
  - name: build-image-for-mockconsumer
    taskRef:
      name: t-buildah-with-resource-setting
    params:
    - name: IMAGE
      value: $(params.IMAGE-MOCKCONSUMER)
    - name: IMAGE_TAG
      value: $(params.pr-number)
    - name: DOCKERFILE
      value: $(params.DOCKERFILE-MOCKCONSUMER)
    - name: CONTEXT
      value: $(params.CONTEXT-MOCKCONSUMER)
    - name: IMAGE_REGISTRY
      value: $(params.IMAGE_REGISTRY)
    workspaces:
    - name: source
      workspace: shared-workspace
    runAfter:
    - generate-id
  - name: fetch-gitops-repo-as-input
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    - name: output
      workspace: input
    params:
    - name: url
      value: $(params.git-url-destination)
    - name: subdirectory
      value: $(params.subdirectory-destination)
    - name: deleteExisting
      value: "true"
    - name: revision
      value: $(params.git-revision-destination)  
    runAfter:
    - build-image-for-mockconsumer
    - build-image-for-mockproducer
  - name: yq-replace-image-tag
    taskRef:
      name: t-yq
    workspaces:
    - name: source
      workspace: input
    params:
    - name: commands
      value: $(params.yq-command)
    runAfter:
    - fetch-gitops-repo-as-input
  - name: fetch-gitops-repo-as-source
    taskRef:
      name: git-cli
      kind: ClusterTask
    workspaces:
    - name: source
      workspace: source
    - name: input
      workspace: input
    params:
    - name: GIT_SCRIPT
      value: $(params.GIT_SCRIPT)
    runAfter:
    - yq-replace-image-tag