# Generated by Django 4.1.3 on 2022-11-29 21:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ride_producerapi_auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='apikey',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
