'use strict';
const options= require('pipeline-cli').Util.parseArguments()
const changeId = options.pr //aka pull-request
const standby = options.standby //aka blue-green target
const name = 'rsbc-ride'

const phases = {
  build: {namespace:'be5301-tools',
       name: `${name}`,
       phase: 'build',
       changeId:changeId,
       suffix: `-build-${changeId}`,
       instance: `${name}-build-${changeId}`,
       tag:`build-${changeId}`
  },
  pr: {namespace:'be5301-dev',
       name: `${name}`,
       phase: 'pr',
       changeId: changeId,
       suffix: `-pr-${changeId}`,
       hostname_suffix: `-pr-${changeId}`,
       instance: `${name}-pr-${changeId}`,
       tag: `pr-${changeId}`,
       log_level: 'DEBUG',
       splunk_url: 'https://hec.monitoring.ag.gov.bc.ca:8088',
       splunk_token: 'eca39c5f-bdd9-41c4-b1cc-215031c42d97',
       splunk_channel: '00872DC6-AC83-4EDE-8AFE-8413C3825C4C',
       cpu_request: '10m',
       cpu_limit: '150m',
       memory_request: '256Mi',
       memory_limit: '512Mi',
       replicas: '1',
       mocksvc_url: 'http://jh-etk-mocksvc-dev.apps.silver.devops.gov.bc.ca/mocksvc/v3'
  },
  dev: {namespace:'be5301-dev',
       name: `${name}`,
       phase: 'dev',
       changeId:changeId,
       suffix: `-dev`,
       hostname_suffix: `-dev`,
       instance: `${name}-dev`,
       tag:`dev`,
       log_level:'DEBUG',
       splunk_url: 'https://hec.monitoring.ag.gov.bc.ca:8088',
       splunk_token: 'eca39c5f-bdd9-41c4-b1cc-215031c42d97',
       splunk_channel: '00872DC6-AC83-4EDE-8AFE-8413C3825C4C',
       cpu_request: '10m',
       cpu_limit: '200m',
       memory_request: '256Mi',
       memory_limit: '1Gi',
       replicas: '1',
       mocksvc_url: 'http://jh-etk-mocksvc-dev.apps.silver.devops.gov.bc.ca/mocksvc/v3'
  },
  stage: {namespace:'be5301-test',
       name: `${name}`,
       phase: 'stage',
       changeId:changeId,
       suffix: `-stage${standby}`,
       hostname_suffix_active: `-stage`,
       hostname_suffix: `-stage-standby`,
       instance: `${name}-stage`,
       tag:`stage`,
       log_level:'DEBUG',
       splunk_url: 'https://hec.monitoring.ag.gov.bc.ca:8088',
       splunk_token: '99b687ff-0e9d-4b70-ac36-2bc2daf31ac7',
       splunk_channel: '00872DC6-AC83-4EDE-8AFE-8413C3825C4C',
       cpu_request: '10m',
       cpu_limit: '200m',
       memory_request: '256Mi',
       memory_limit: '1Gi',
       replicas: '1',
       mocksvc_url: 'http://jh-etk-mocksvc-stage.apps.silver.devops.gov.bc.ca/mocksvc/v3'
  },
  test: {namespace:'be5301-test',
       name: `${name}`,
       phase: 'test',
       changeId:changeId,
       suffix: `-test`,
       hostname_suffix: `-test`,
       instance: `${name}-test`,
       tag:`test`,
       log_level:'DEBUG',
       splunk_url: 'https://hec.monitoring.ag.gov.bc.ca:8088',
       splunk_token: '99b687ff-0e9d-4b70-ac36-2bc2daf31ac7',
       splunk_channel: '00872DC6-AC83-4EDE-8AFE-8413C3825C4C',
       cpu_request: '10m',
       cpu_limit: '200m',
       memory_request: '256Mi',
       memory_limit: '1Gi',
       replicas: '1',
       mocksvc_url: 'http://jh-etk-mocksvc-test.apps.silver.devops.gov.bc.ca/mocksvc/v3'
  },
  prod: {namespace:'be5301-prod',
       name: `${name}`,
       phase: 'prod',
       changeId:changeId,
       suffix: `-prod${standby}`,
       hostname_suffix_active: '-prod',
       hostname_suffix: '-prod-standby',
       instance: `${name}-prod`,
       tag:`prod`,
       log_level:'INFO',
       splunk_url: 'https://hec.monitoring.ag.gov.bc.ca:8088',
       splunk_token: '7805be39-9fd1-4d46-b812-619277398160',
       splunk_channel: '00872DC6-AC83-4EDE-8AFE-8413C3825C4C',
       cpu_request: '10m',
       cpu_limit: '200m',
       memory_request: '256Mi',
       memory_limit: '1Gi',
       replicas: '1',
       mocksvc_url: 'http://jh-etk-mocksvc.apps.silver.devops.gov.bc.ca/mocksvc/v3'
  },
};

// This callback forces the node process to exit as failure.
process.on('unhandledRejection', (reason) => {
  console.log(reason);
  process.exit(1);
});

module.exports = exports = {phases, options};
