'use strict';
const options= require('pipeline-cli').Util.parseArguments()
const changeId = options.pr //aka pull-request
const standby = options.standby //aka blue-green target
const name = 'rsbc-ride'

const phases = {
  build: {namespace:'be5301-tools',
       name: `${name}`,
       phase: 'build',
       changeId:changeId,
       suffix: `-build-${changeId}`,
       instance: `${name}-build-${changeId}`,
       tag:`build-${changeId}`
  },
  pr: {namespace:'be5301-dev',
       name: `${name}`,
       phase: 'pr',
       changeId: changeId,
       suffix: `-pr-${changeId}`,
       hostname_suffix: `-pr-${changeId}`,
       instance: `${name}-pr-${changeId}`,
       tag: `pr-${changeId}`,
       custom_error_emailto: 'curtis.stodgell@gov.bc.ca, Echo.2.Liang@gov.bc.ca',
       custom_error_emailfrom: `rsbc-ride@pr-${changeId} <donotreply@gov.bc.ca>`,
       custom_error_url_prefix: `https://rsbc-ride-scweb-pr-${changeId}.apps.silver.devops.gov.bc.ca/restricted/errorDetails/`,
       log_level: 'DEBUG',
       splunk_url: 'https://hec.monitoring.ag.gov.bc.ca:8088',
       splunk_token: 'eca39c5f-bdd9-41c4-b1cc-215031c42d97',
       splunk_channel: '00872DC6-AC83-4EDE-8AFE-8413C3825C4C',
       cpu_request: '10m',
       cpu_limit: '150m',
       memory_request: '256Mi',
       memory_limit: '512Mi',
       replicas: '1'
  },
  dev: {namespace:'be5301-dev',
       name: `${name}`,
       phase: 'dev',
       changeId:changeId,
       suffix: `-dev`,
       hostname_suffix: `-dev`,
       instance: `${name}-dev`,
       tag:`dev`,
       custom_error_emailto: 'curtis.stodgell@gov.bc.ca, Echo.2.Liang@gov.bc.ca',
       custom_error_emailfrom: `rsbc-ride@dev <donotreply@gov.bc.ca>`,
       custom_error_url_prefix: `https://rsbc-ride-scweb-dev.apps.silver.devops.gov.bc.ca/restricted/errorDetails/`,
       log_level:'DEBUG',
       splunk_url: 'https://hec.monitoring.ag.gov.bc.ca:8088',
       splunk_token: 'eca39c5f-bdd9-41c4-b1cc-215031c42d97',
       splunk_channel: '00872DC6-AC83-4EDE-8AFE-8413C3825C4C',
       cpu_request: '10m',
       cpu_limit: '200m',
       memory_request: '256Mi',
       memory_limit: '1Gi',
       replicas: '1'
  },
  stage: {namespace:'be5301-test',
       name: `${name}`,
       phase: 'stage',
       changeId:changeId,
       suffix: `-stage${standby}`,
       hostname_suffix_active: `-stage`,
       hostname_suffix: `-stage-standby`,
       instance: `${name}-stage`,
       tag:`stage`,
       custom_error_emailto: 'curtis.stodgell@gov.bc.ca, Echo.2.Liang@gov.bc.ca, Ayo.Ojo@gov.bc.ca, Steve.1.Forsyth@gov.bc.ca',
       custom_error_emailfrom: `rsbc-ride@stage <donotreply@gov.bc.ca>`,
       custom_error_url_prefix: `https://rsbc-ride-scweb-stage.apps.silver.devops.gov.bc.ca/restricted/errorDetails/`,
       log_level:'DEBUG',
       splunk_url: 'https://hec.monitoring.ag.gov.bc.ca:8088',
       splunk_token: '99b687ff-0e9d-4b70-ac36-2bc2daf31ac7',
       splunk_channel: '00872DC6-AC83-4EDE-8AFE-8413C3825C4C',
       cpu_request: '10m',
       cpu_limit: '200m',
       memory_request: '256Mi',
       memory_limit: '1Gi',
       replicas: '1'
  },
  test: {namespace:'be5301-test',
       name: `${name}`,
       phase: 'test',
       changeId:changeId,
       suffix: `-test`,
       hostname_suffix: `-test`,
       instance: `${name}-test`,
       tag:`test`,
       custom_error_emailto: 'curtis.stodgell@gov.bc.ca, Echo.2.Liang@gov.bc.ca, Ayo.Ojo@gov.bc.ca, Steve.1.Forsyth@gov.bc.ca',
       custom_error_emailfrom: `rsbc-ride@test <donotreply@gov.bc.ca>`,
       custom_error_url_prefix: `https://rsbc-ride-scweb-test.apps.silver.devops.gov.bc.ca/restricted/errorDetails/`,
       log_level:'DEBUG',
       splunk_url: 'https://hec.monitoring.ag.gov.bc.ca:8088',
       splunk_token: '99b687ff-0e9d-4b70-ac36-2bc2daf31ac7',
       splunk_channel: '00872DC6-AC83-4EDE-8AFE-8413C3825C4C',
       cpu_request: '10m',
       cpu_limit: '200m',
       memory_request: '256Mi',
       memory_limit: '1Gi',
       replicas: '1'
  },
  prod: {namespace:'be5301-prod',
       name: `${name}`,
       phase: 'prod',
       changeId:changeId,
       suffix: `-prod${standby}`,
       hostname_suffix_active: '-prod',
       hostname_suffix: '-prod-standby',
       instance: `${name}-prod`,
       tag:`prod`,
       custom_error_emailto: 'RSIOpsSupport@gov.bc.ca',
       custom_error_emailfrom: `rsbc-ride <donotreply@gov.bc.ca>`,
       custom_error_url_prefix: `https://rsbc-ride-scweb.apps.silver.devops.gov.bc.ca/restricted/errorDetails/`,
       log_level:'INFO',
       splunk_url: 'https://hec.monitoring.ag.gov.bc.ca:8088',
       splunk_token: '7805be39-9fd1-4d46-b812-619277398160',
       splunk_channel: '00872DC6-AC83-4EDE-8AFE-8413C3825C4C',
       cpu_request: '10m',
       cpu_limit: '200m',
       memory_request: '256Mi',
       memory_limit: '1Gi',
       replicas: '1'
  },
};

// This callback forces the node process to exit as failure.
process.on('unhandledRejection', (reason) => {
  console.log(reason);
  process.exit(1);
});

module.exports = exports = {phases, options};
