'use strict';
const options= require('pipeline-cli').Util.parseArguments()
const changeId = options.pr //aka pull-request
const standby = options.standby //aka blue-green target
const name = 'jh-etk'

const phases = {
  build: {namespace:'be5301-tools',
       name: `${name}`,
       dbname: `${name}-patroni-db-image`,
       phase: 'build',
       changeId:changeId,
       suffix: `-build-${changeId}`,
       instance: `${name}-build-${changeId}`,
       tag:`build-${changeId}`
  },
  pr: {namespace:'be5301-dev',
       name: `${name}`,
       phase: 'pr',
       changeId: changeId,
       suffix: `-pr-${changeId}`,
       hostname_suffix: `-pr-${changeId}`,
       instance: `${name}-pr-${changeId}`,
       tag: `pr-${changeId}`,
       custom_error_emailto: 'curtis.stodgell@gov.bc.ca, Echo.2.Liang@gov.bc.ca',
       custom_error_emailfrom: `JH-ETK@pr-${changeId} <donotreply@gov.bc.ca>`,
       custom_error_url_prefix: `https://jh-etk-scweb-pr-${changeId}.apps.silver.devops.gov.bc.ca/restricted/errorDetails/`,
       sftp_server_host: 'sfeg.test.ag.gov.bc.ca',
       paymentsvc_route_host: `jh-etk-paybcadapter-pr-${changeId}.apps.silver.devops.gov.bc.ca`,
       paymentsvc_route_host_standby: `jh-etk-paybcadapter-pr-${changeId}.apps.silver.devops.gov.bc.ca`,
       rcmpadapter_route_host: `jh-etk-rcmpadapter-pr-${changeId}.apps.silver.devops.gov.bc.ca`,
       rcmpadapter_route_host_standby: `jh-etk-rcmpadapter-pr-${changeId}.apps.silver.devops.gov.bc.ca`,
       justin_interface_access_token_uri: 'https://wsgw.dev.jag.gov.bc.ca/keycloak/auth/realms/isb-api/protocol/openid-connect/token',
       justin_interface_ticket_dispute_uri: `http://jh-etk-mocksvc-pr-${changeId}:8080/mocksvc/v3/justin/api/v1/citations/`,
       justin_interface_status_update_uri: `http://jh-etk-mocksvc-pr-${changeId}:8080/mocksvc/v3/justin/api/v1/citations/`,
       justin_interface_dispute_court_results_uri: `http://jh-etk-mocksvc-pr-${changeId}:8080/mocksvc/v3/justin/api/v1/disputeCourtResults/`,
       justin_interface_uri_dispute_court_results_notify_process_status_uri: `http://jh-etk-mocksvc-pr-${changeId}:8080/mocksvc/v3/justin/api/v1/notifyProcessStatus/`,
       keycloak_url: 'https://dev.oidc.gov.bc.ca/auth',
       configured_scweb_hostname: `jh-etk-scweb-pr-${changeId}.apps.silver.devops.gov.bc.ca`,
       configured_scweb_hostname_standby: `jh-etk-scweb-pr-${changeId}.apps.silver.devops.gov.bc.ca`,
       configured_rideweb_hostname: `ride-pr-${changeId}.apps.silver.devops.gov.bc.ca`,
       configured_rideweb_hostname_standby: `ride-pr-${changeId}.apps.silver.devops.gov.bc.ca`,
       configured_ridesvc_hostname: `jh-cmn-ridesvc-pr-${changeId}.apps.silver.devops.gov.bc.ca`,
       configured_ridesvc_hostname_standby: `jh-cmn-ridesvc-pr-${changeId}.apps.silver.devops.gov.bc.ca`,
       sso_admin_endpoint: 'https://dev.oidc.gov.bc.ca/auth/admin/justicehub/console/',
       paybc_individual_invoice_endpoint_url_prefix: `http://jh-etk-paymentsvc-pr-${changeId}:8080/payment/v3`,
       icbc_paymentservice_endpoint_uri: `http://jh-etk-mocksvc-pr-${changeId}:8080/mocksvc/v3/rest/PSSGVPHPAYBC/vph/rcpts`,
       icbc_issuanceservice_endpoint_uri: `http://jh-etk-mocksvc-pr-${changeId}:8080/mocksvc/v3/ws`,
       icbc_pingservice_endpoint_uri: `http://jh-etk-mocksvc-pr-${changeId}:8080/mocksvc/v3/icbc/utility/echo`,
       ftp_instance_folder_cleanup_yn: 'N',
       log_level: 'DEBUG',
       splunk_url: 'https://hec.monitoring.ag.gov.bc.ca:8088',
       splunk_token: 'eca39c5f-bdd9-41c4-b1cc-215031c42d97',
       splunk_channel: '00872DC6-AC83-4EDE-8AFE-8413C3825C4C',
       cpu_request: '10m',
       cpu_limit: '150m',
       memory_request: '256Mi',
       memory_limit: '512Mi',
       scweb_cpu_request: '10m',
       scweb_cpu_limit: '200m',
       scweb_memory_request: '256Mi',
       scweb_memory_limit: '512Mi',
       db_cpu_limit: '200m',
       db_memory_request: '256Mi',
       db_memory_limit: '512Mi',
       icbc_sftp_server_host: 'ftpdev.icbc.com',
       justin_interface_mockYN: 'Y',
       java_max_mem_ratio: '80',
       replicas: '1',
       biadapter_geocoder_api_url: `http://jh-etk-geocodersvc-pr-${changeId}:5000/address`,
	   biadapter_bi_db_host: 'notset',
	   biadapter_bi_db_name: 'notset',
        etk_splunk_dashboard_url: 'https://jag.gov.bc.ca/splunk/en-US/app/road_safety/rsbc_eticketing?form.timerange.earliest=%40w0&form.timerange.latest=now&form.indexval=dev_rsi&hideFilters=true',
        openshift_url: 'https://console.apps.silver.devops.gov.bc.ca/k8s/cluster/projects/be5301-dev'
  },
  dev: {namespace:'be5301-dev',
       name: `${name}`,
       phase: 'dev',
       changeId:changeId,
       suffix: `-dev`,
       hostname_suffix: `-dev`,
       instance: `${name}-dev`,
       tag:`dev`,
       custom_error_emailto: 'curtis.stodgell@gov.bc.ca, Echo.2.Liang@gov.bc.ca',
       custom_error_emailfrom: `JH-ETK@dev <donotreply@gov.bc.ca>`,
       custom_error_url_prefix: `https://jh-etk-scweb-dev.apps.silver.devops.gov.bc.ca/restricted/errorDetails/`,
       sftp_server_host: 'sfeg.test.ag.gov.bc.ca',
       paymentsvc_route_host: 'jh-etk-paybcadapter-dev.ride.bcgov',
       paymentsvc_route_host_standby: 'jh-etk-paybcadapter-dev.ride.bcgov',
       rcmpadapter_route_host: 'jh-etk-rcmpadapter-dev.ride.bcgov',
       rcmpadapter_route_host_standby: 'jh-etk-rcmpadapter-dev.ride.bcgov',
       justin_interface_access_token_uri: 'https://wsgw.test.jag.gov.bc.ca/keycloak/auth/realms/isb-api/protocol/openid-connect/token',
       justin_interface_ticket_dispute_uri: 'https://wsgw.dev.jag.gov.bc.ca/justin/api/v1/citations/',
       justin_interface_status_update_uri: 'https://wsgw.dev.jag.gov.bc.ca/justin/api/v1/citations/',
       justin_interface_dispute_court_results_uri: 'https://wsgw.dev.jag.gov.bc.ca/justin/api/v1/disputeCourtResults/',
       justin_interface_uri_dispute_court_results_notify_process_status_uri: 'https://wsgw.dev.jag.gov.bc.ca/justin/api/v1/notifyProcessStatus/',
       keycloak_url: 'https://dev.oidc.gov.bc.ca/auth',
       configured_scweb_hostname: `jh-etk-scweb-dev.apps.silver.devops.gov.bc.ca`,
       configured_scweb_hostname_standby: `jh-etk-scweb-dev.apps.silver.devops.gov.bc.ca`,
       configured_rideweb_hostname: `ride-dev.apps.silver.devops.gov.bc.ca`,
       configured_rideweb_hostname_standby: `ride-dev.apps.silver.devops.gov.bc.ca`,
       configured_ridesvc_hostname: `jh-cmn-ridesvc-dev.apps.silver.devops.gov.bc.ca`,
       configured_ridesvc_hostname_standby: `jh-cmn-ridesvc-dev.apps.silver.devops.gov.bc.ca`,
       sso_admin_endpoint: 'https://dev.oidc.gov.bc.ca/auth/admin/justicehub/console/',
       ssg_whitelist: '142.34.5.73 142.34.5.68',
       paybc_individual_invoice_endpoint_url_prefix: 'https://wsgw.dev.jag.gov.bc.ca/paybc/vph',
       icbc_paymentservice_endpoint_uri: 'https://wsgw.dev.jag.gov.bc.ca:8443/icbc/api/rest/finance',
       //icbc_issuanceservice_endpoint_uri: 'https://wsgw.dev.jag.gov.bc.ca:8443/icbc/api/soap/RSI_InformationManager',
       icbc_issuanceservice_endpoint_uri: `http://jh-etk-mocksvc-dev:8080/mocksvc/v3/ws`,
       icbc_pingservice_endpoint_uri: `http://jh-etk-mocksvc-dev:8080/mocksvc/v3/icbc/utility/echo`,
       ftp_instance_folder_cleanup_yn: 'N',
       log_level:'DEBUG',
       splunk_url: 'https://hec.monitoring.ag.gov.bc.ca:8088',
       splunk_token: 'eca39c5f-bdd9-41c4-b1cc-215031c42d97',
       splunk_channel: '00872DC6-AC83-4EDE-8AFE-8413C3825C4C',
       cpu_request: '10m',
       cpu_limit: '200m',
       memory_request: '256Mi',
       memory_limit: '1Gi',
       scweb_cpu_request: '10m',
       scweb_cpu_limit: '200m',
       scweb_memory_request: '256Mi',
       scweb_memory_limit: '1Gi',
       db_cpu_limit: '200m',
       db_memory_request: '256Mi',
       db_memory_limit: '1Gi',
       icbc_sftp_server_host: 'ftpdev.icbc.com',
       justin_interface_mockYN: 'N',
       java_max_mem_ratio: '80',
       replicas: '1',
       biadapter_geocoder_api_url: 'http://jh-etk-geocodersvc-dev:5000/address',
	   biadapter_bi_db_host: 'notset',
	   biadapter_bi_db_name: 'notset',
        etk_splunk_dashboard_url: 'https://jag.gov.bc.ca/splunk/en-US/app/road_safety/rsbc_eticketing?form.timerange.earliest=%40w0&form.timerange.latest=now&form.indexval=dev_rsi&hideFilters=true',
        openshift_url: 'https://console.apps.silver.devops.gov.bc.ca/k8s/cluster/projects/be5301-dev'
  },
  stage: {namespace:'be5301-test',
       name: `${name}`,
       phase: 'stage',
       changeId:changeId,
       suffix: `-stage${standby}`,
       hostname_suffix_active: `-stage`,
       hostname_suffix: `-stage-standby`,
       instance: `${name}-stage`,
       tag:`stage`,
       custom_error_emailto: 'curtis.stodgell@gov.bc.ca, Echo.2.Liang@gov.bc.ca, Ayo.Ojo@gov.bc.ca, Steve.1.Forsyth@gov.bc.ca',
       custom_error_emailfrom: `JH-ETK@stage <donotreply@gov.bc.ca>`,
       custom_error_url_prefix: `https://jh-etk-scweb-stage.apps.silver.devops.gov.bc.ca/restricted/errorDetails/`,
       sftp_server_host: 'sfeg.test.ag.gov.bc.ca',
       paymentsvc_route_host: 'jh-etk-paybcadapter-stage.ride.bcgov',
       paymentsvc_route_host_standby: 'jh-etk-paybcadapter-stage-standby.apps.silver.devops.gov.bc.ca',
       rcmpadapter_route_host: 'jh-etk-rcmpadapter-stage.ride.bcgov',
       rcmpadapter_route_host_standby: 'jh-etk-rcmpadapter-stage-standby.apps.silver.devops.gov.bc.ca',
       configured_scweb_hostname: `jh-etk-scweb-stage.apps.silver.devops.gov.bc.ca`,
       configured_scweb_hostname_standby: `jh-etk-scweb-stage-standby.apps.silver.devops.gov.bc.ca`,
       configured_rideweb_hostname: `ride-stage.apps.silver.devops.gov.bc.ca`,
       configured_rideweb_hostname_standby: `ride-stage-standby.apps.silver.devops.gov.bc.ca`,
       configured_ridesvc_hostname: `jh-cmn-ridesvc-stage.apps.silver.devops.gov.bc.ca`,
       configured_ridesvc_hostname_standby: `jh-cmn-ridesvc-stage-standby.apps.silver.devops.gov.bc.ca`,
       sso_admin_endpoint: 'https://test.oidc.gov.bc.ca/auth/admin/justicehub/console/',
       haproxy_timeout: '50s',
       justin_interface_access_token_uri: 'https://wsgw.test.jag.gov.bc.ca/keycloak/auth/realms/isb-api/protocol/openid-connect/token',
       justin_interface_ticket_dispute_uri: 'https://wsgw.test.jag.gov.bc.ca/justin/api/v1/citations/',
       justin_interface_status_update_uri: 'https://wsgw.test.jag.gov.bc.ca/justin/api/v1/citations/',
       justin_interface_dispute_court_results_uri: 'https://wsgw.test.jag.gov.bc.ca/justin/api/v1/disputeCourtResults/',
       justin_interface_uri_dispute_court_results_notify_process_status_uri: 'https://wsgw.test.jag.gov.bc.ca/justin/api/v1/notifyProcessStatus/',
       keycloak_url: 'https://test.oidc.gov.bc.ca/auth',
       paybc_individual_invoice_endpoint_url_prefix: `http://jh-etk-paymentsvc-stage${standby}:8080/payment/v3`,
       //icbc_paymentservice_endpoint_uri: 'https://wsgw.test.jag.gov.bc.ca:8443/icbc/api/rest/finance',
       icbc_paymentservice_endpoint_uri: `http://jh-etk-mocksvc-stage${standby}:8080/mocksvc/v3/rest/PSSGVPHPAYBC/vph/rcpts`,
       //icbc_issuanceservice_endpoint_uri: 'https://wsgw.test.jag.gov.bc.ca:8443/icbc/api/soap/RSI_InformationManager',
       icbc_issuanceservice_endpoint_uri: `http://jh-etk-mocksvc-stage${standby}:8080/mocksvc/v3/ws`,
       icbc_pingservice_endpoint_uri: `http://jh-etk-mocksvc-stage${standby}:8080/mocksvc/v3/icbc/utility/echo`,
       ftp_instance_folder_cleanup_yn: 'N',
       log_level:'DEBUG',
       splunk_url: 'https://hec.monitoring.ag.gov.bc.ca:8088',
       splunk_token: '99b687ff-0e9d-4b70-ac36-2bc2daf31ac7',
       splunk_channel: '00872DC6-AC83-4EDE-8AFE-8413C3825C4C',
       cpu_request: '10m',
       cpu_limit: '200m',
       memory_request: '256Mi',
       memory_limit: '1Gi',
       scweb_cpu_request: '10m',
       scweb_cpu_limit: '200m',
       scweb_memory_request: '256Mi',
       scweb_memory_limit: '1Gi',
       db_cpu_limit: '200m',
       db_memory_request: '256Mi',
       db_memory_limit: '1Gi',
       icbc_sftp_server_host: 'ftpdev.icbc.com',
       justin_interface_mockYN: 'N',
       java_max_mem_ratio: '80',
       replicas: '1',
       biadapter_geocoder_api_url: `http://jh-etk-geocodersvc-stage${standby}:5000/address`,
	   biadapter_bi_db_host: 'notset',
	   biadapter_bi_db_name: 'notset',
        etk_splunk_dashboard_url: 'https://jag.gov.bc.ca/splunk/en-US/app/road_safety/rsbc_eticketing?form.timerange.earliest=%40w0&form.timerange.latest=now&form.indexval=dev_rsi&hideFilters=true',
        openshift_url: 'https://console.apps.silver.devops.gov.bc.ca/k8s/cluster/projects/be5301-test'
  },
  test: {namespace:'be5301-test',
       name: `${name}`,
       phase: 'test',
       changeId:changeId,
       suffix: `-test`,
       hostname_suffix: `-test`,
       instance: `${name}-test`,
       tag:`test`,
       custom_error_emailto: 'curtis.stodgell@gov.bc.ca, Echo.2.Liang@gov.bc.ca, Ayo.Ojo@gov.bc.ca, Steve.1.Forsyth@gov.bc.ca',
       custom_error_emailfrom: `JH-ETK@test <donotreply@gov.bc.ca>`,
       custom_error_url_prefix: `https://jh-etk-scweb-test.apps.silver.devops.gov.bc.ca/restricted/errorDetails/`,
       sftp_server_host: 'sfeg.test.ag.gov.bc.ca',
       paymentsvc_route_host: 'jh-etk-paybcadapter-test.ride.bcgov',
       paymentsvc_route_host_standby: 'jh-etk-paybcadapter-test.ride.bcgov',
       rcmpadapter_route_host: 'jh-etk-rcmpadapter-test.ride.bcgov',
       rcmpadapter_route_host_standby: 'jh-etk-rcmpadapter-test.ride.bcgov',
       haproxy_whitelist: '142.34.5.0/26 142.34.140.0/26',
       haproxy_timeout: '50s',
       ssg_whitelist: '142.34.5.132 142.34.5.133 142.34.5.141 142.34.5.139',
       justin_interface_access_token_uri: 'https://wsgw.test.jag.gov.bc.ca/keycloak/auth/realms/isb-api/protocol/openid-connect/token',
       justin_interface_ticket_dispute_uri: 'https://wsgw.test.jag.gov.bc.ca/justin/api/v1/citations/',
       justin_interface_status_update_uri: 'https://wsgw.test.jag.gov.bc.ca/justin/api/v1/citations/',
       justin_interface_dispute_court_results_uri: 'https://wsgw.test.jag.gov.bc.ca/justin/api/v1/disputeCourtResults/',
       justin_interface_uri_dispute_court_results_notify_process_status_uri: 'https://wsgw.test.jag.gov.bc.ca/justin/api/v1/notifyProcessStatus/',
       keycloak_url: 'https://test.oidc.gov.bc.ca/auth',
       configured_scweb_hostname: `jh-etk-scweb-test.apps.silver.devops.gov.bc.ca`, 
       configured_scweb_hostname_standby: `jh-etk-scweb-test.apps.silver.devops.gov.bc.ca`,
       configured_rideweb_hostname: `ride-test.apps.silver.devops.gov.bc.ca`,
       configured_rideweb_hostname_standby: `ride-test.apps.silver.devops.gov.bc.ca`,
       configured_ridesvc_hostname: `jh-cmn-ridesvc-test.apps.silver.devops.gov.bc.ca`,
       configured_ridesvc_hostname_standby: `jh-cmn-ridesvc-test.apps.silver.devops.gov.bc.ca`,
       sso_admin_endpoint: 'https://test.oidc.gov.bc.ca/auth/admin/justicehub/console/',
       paybc_individual_invoice_endpoint_url_prefix: 'https://wsgw.test.jag.gov.bc.ca/paybc/vph',
       icbc_paymentservice_endpoint_uri: 'https://wsgw.test.jag.gov.bc.ca:8443/icbc/api/rest/finance',
       //icbc_issuanceservice_endpoint_uri: 'https://wsgw.test.jag.gov.bc.ca:8443/icbc/api/soap/RSI_InformationManager',
       icbc_issuanceservice_endpoint_uri: `http://jh-etk-mocksvc-test:8080/mocksvc/v3/ws`,
       icbc_pingservice_endpoint_uri: `http://jh-etk-mocksvc-test:8080/mocksvc/v3/icbc/utility/echo`,
       ftp_instance_folder_cleanup_yn: 'N',
       log_level:'DEBUG',
       splunk_url: 'https://hec.monitoring.ag.gov.bc.ca:8088',
       splunk_token: '99b687ff-0e9d-4b70-ac36-2bc2daf31ac7',
       splunk_channel: '00872DC6-AC83-4EDE-8AFE-8413C3825C4C',
       cpu_request: '10m',
       cpu_limit: '200m',
       memory_request: '256Mi',
       memory_limit: '1Gi',
       scweb_cpu_request: '10m',
       scweb_cpu_limit: '1',
       scweb_memory_request: '256Mi',
       scweb_memory_limit: '2Gi',
       db_cpu_limit: '200m',
       db_memory_request: '256Mi',
       db_memory_limit: '1Gi',
       icbc_sftp_server_host: 'ftpdev.icbc.com',
       justin_interface_mockYN: 'N',
       java_max_mem_ratio: '80',
       replicas: '1',
       biadapter_geocoder_api_url: 'http://jh-etk-geocodersvc-test:5000/address',
	   biadapter_bi_db_host: '142.34.108.53',
	   biadapter_bi_db_name: 'rsbcodw',
        etk_splunk_dashboard_url: 'https://jag.gov.bc.ca/splunk/en-US/app/road_safety/rsbc_eticketing?form.timerange.earliest=%40w0&form.timerange.latest=now&form.indexval=test_rsi&hideFilters=true',
        openshift_url: 'https://console.apps.silver.devops.gov.bc.ca/k8s/cluster/projects/be5301-test'
  },
  prod: {namespace:'be5301-prod',
       name: `${name}`,
       phase: 'prod',
       changeId:changeId,
       suffix: `-prod${standby}`,
       hostname_suffix_active: '-prod',
       hostname_suffix: '-prod-standby',
       instance: `${name}-prod`,
       tag:`prod`,
       custom_error_emailto: 'RSIOpsSupport@gov.bc.ca',
       custom_error_emailfrom: `JH-ETK <donotreply@gov.bc.ca>`,
       custom_error_url_prefix: `https://jh-etk-scweb.apps.silver.devops.gov.bc.ca/restricted/errorDetails/`,
       sftp_server_host: 'sfeg.ag.gov.bc.ca',
       paymentsvc_route_host: `jh-etk-paybcadapter-prod.ride.bcgov`,
       paymentsvc_route_host_standby: `jh-etk-paybcadapter-prod-standby.apps.silver.devops.gov.bc.ca`,
       rcmpadapter_route_host: `jh-etk-rcmpadapter-prod.ride.bcgov`,
       rcmpadapter_route_host_standby: `jh-etk-rcmpadapter-prod-standby.apps.silver.devops.gov.bc.ca`,
       configured_scweb_hostname: 'jh-etk-scweb.apps.silver.devops.gov.bc.ca',
       configured_scweb_hostname_standby: 'jh-etk-scweb-standby.apps.silver.devops.gov.bc.ca',
       configured_rideweb_hostname: `ride.apps.silver.devops.gov.bc.ca`,
       configured_rideweb_hostname_standby: `ride-standby.apps.silver.devops.gov.bc.ca`,
       configured_ridesvc_hostname: `jh-cmn-ridesvc.apps.silver.devops.gov.bc.ca`,
       configured_ridesvc_hostname_standby: `jh-cmn-ridesvc-standby.apps.silver.devops.gov.bc.ca`,
       sso_admin_endpoint: 'https://oidc.gov.bc.ca/auth/admin/justicehub/console/',
       haproxy_whitelist: '142.34.5.0/26 142.34.140.0/26',
       ssg_whitelist: '142.34.134.132 142.34.134.133 142.34.134.138 142.34.134.140',
       haproxy_timeout: '50s',
       justin_interface_access_token_uri: 'https://wsgw.jag.gov.bc.ca/keycloak/auth/realms/isb-api/protocol/openid-connect/token',
       justin_interface_ticket_dispute_uri: 'https://wsgw.jag.gov.bc.ca/justin/api/v1/citations/',
       justin_interface_status_update_uri: 'https://wsgw.jag.gov.bc.ca/justin/api/v1/citations/',
       justin_interface_dispute_court_results_uri: 'https://wsgw.jag.gov.bc.ca/justin/api/v1/disputeCourtResults/',
       justin_interface_uri_dispute_court_results_notify_process_status_uri: 'https://wsgw.jag.gov.bc.ca/justin/api/v1/notifyProcessStatus/',
       keycloak_url: 'https://oidc.gov.bc.ca/auth',
       paybc_individual_invoice_endpoint_url_prefix: 'https://wsgw.jag.gov.bc.ca/paybc/vph',
       icbc_paymentservice_endpoint_uri: 'https://wsgw.jag.gov.bc.ca:8443/icbc/api/rest/finance',
       icbc_issuanceservice_endpoint_uri: 'https://wsgw.jag.gov.bc.ca:8443/icbc/api/soap/RSI_InformationManager',
       icbc_pingservice_endpoint_uri: `https://wsgw.jag.gov.bc.ca:8443/icbc/utility/echo`,
       ftp_instance_folder_cleanup_yn: 'N',
       log_level:'INFO',
       splunk_url: 'https://hec.monitoring.ag.gov.bc.ca:8088',
       splunk_token: '7805be39-9fd1-4d46-b812-619277398160',
       splunk_channel: '00872DC6-AC83-4EDE-8AFE-8413C3825C4C',
       cpu_request: '10m',
       cpu_limit: '200m',
       memory_request: '256Mi',
       memory_limit: '1Gi',
       scweb_cpu_request: '10m',
       scweb_cpu_limit: '1',
       scweb_memory_request: '1Gi',
       scweb_memory_limit: '2Gi',
       db_cpu_limit: '500m',
       db_memory_request: '512Mi',
       db_memory_limit: '2Gi',
       icbc_sftp_server_host: 'ftp2.icbc.com',
       justin_interface_mockYN: 'N',
       java_max_mem_ratio: '80',
       replicas: '1',
       biadapter_geocoder_api_url: `http://jh-etk-geocodersvc-prod${standby}:5000/address`,
       biadapter_bi_db_host: '142.34.254.5',
	   biadapter_bi_db_name: 'rsbcodw',
        etk_splunk_dashboard_url: 'https://jag.gov.bc.ca/splunk/en-US/app/road_safety/rsbc_eticketing?form.timerange.earliest=%40w0&form.timerange.latest=now&form.indexval=prod_rsi&hideFilters=true',
        openshift_url: 'https://console.apps.silver.devops.gov.bc.ca/k8s/cluster/projects/be5301-prod'
  },
};

// This callback forces the node process to exit as failure.
process.on('unhandledRejection', (reason) => {
  console.log(reason);
  process.exit(1);
});

module.exports = exports = {phases, options};
