# Generated by Django 4.1.3 on 2022-11-29 21:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppName',
            fields=[
                ('appname', models.CharField(max_length=210)),
                ('appcode', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('appstatus', models.CharField(choices=[('E', 'Enabled'), ('D', 'Disabled')], max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('apikey', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('appid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ride_producerapi_auth_app.appname')),
            ],
        ),
    ]
