# Generated by Django 4.1.3 on 2022-11-30 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_producerapi_auth_app', '0002_alter_apikey_apikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appname',
            name='appname',
            field=models.CharField(max_length=205),
        ),
    ]
