# Generated by Django 3.2.15 on 2022-11-30 23:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ride_producerapi_auth_app', '0003_alter_appname_appname'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='apikeyval',
            field=models.CharField(default=uuid.uuid5, max_length=200),
        ),
    ]
