# Generated by Django 3.2.15 on 2022-11-30 23:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ride_producerapi_auth_app', '0004_apikey_apikeyval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='apikeyval',
            field=models.CharField(default=uuid.uuid4, max_length=200),
        ),
    ]
