/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package bcgov.rsbc.ride.kafka.evteventproducer.model.payment;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class columnValues extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -2562167250879099917L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"columnValues\",\"namespace\":\"bcgov.rsbc.ride.kafka.evteventproducer.model.payment\",\"fields\":[{\"name\":\"personId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"default\":\"null\"},{\"name\":\"email\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"default\":\"null\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<columnValues> ENCODER =
      new BinaryMessageEncoder<columnValues>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<columnValues> DECODER =
      new BinaryMessageDecoder<columnValues>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<columnValues> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<columnValues> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<columnValues> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<columnValues>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this columnValues to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a columnValues from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a columnValues instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static columnValues fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.String personId;
  @Deprecated public java.lang.String email;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public columnValues() {}

  /**
   * All-args constructor.
   * @param personId The new value for personId
   * @param email The new value for email
   */
  public columnValues(java.lang.String personId, java.lang.String email) {
    this.personId = personId;
    this.email = email;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return personId;
    case 1: return email;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: personId = value$ != null ? value$.toString() : null; break;
    case 1: email = value$ != null ? value$.toString() : null; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'personId' field.
   * @return The value of the 'personId' field.
   */
  public java.lang.String getPersonId() {
    return personId;
  }


  /**
   * Sets the value of the 'personId' field.
   * @param value the value to set.
   */
  public void setPersonId(java.lang.String value) {
    this.personId = value;
  }

  /**
   * Gets the value of the 'email' field.
   * @return The value of the 'email' field.
   */
  public java.lang.String getEmail() {
    return email;
  }


  /**
   * Sets the value of the 'email' field.
   * @param value the value to set.
   */
  public void setEmail(java.lang.String value) {
    this.email = value;
  }

  /**
   * Creates a new columnValues RecordBuilder.
   * @return A new columnValues RecordBuilder
   */
  public static bcgov.rsbc.ride.kafka.evteventproducer.model.payment.columnValues.Builder newBuilder() {
    return new bcgov.rsbc.ride.kafka.evteventproducer.model.payment.columnValues.Builder();
  }

  /**
   * Creates a new columnValues RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new columnValues RecordBuilder
   */
  public static bcgov.rsbc.ride.kafka.evteventproducer.model.payment.columnValues.Builder newBuilder(bcgov.rsbc.ride.kafka.evteventproducer.model.payment.columnValues.Builder other) {
    if (other == null) {
      return new bcgov.rsbc.ride.kafka.evteventproducer.model.payment.columnValues.Builder();
    } else {
      return new bcgov.rsbc.ride.kafka.evteventproducer.model.payment.columnValues.Builder(other);
    }
  }

  /**
   * Creates a new columnValues RecordBuilder by copying an existing columnValues instance.
   * @param other The existing instance to copy.
   * @return A new columnValues RecordBuilder
   */
  public static bcgov.rsbc.ride.kafka.evteventproducer.model.payment.columnValues.Builder newBuilder(bcgov.rsbc.ride.kafka.evteventproducer.model.payment.columnValues other) {
    if (other == null) {
      return new bcgov.rsbc.ride.kafka.evteventproducer.model.payment.columnValues.Builder();
    } else {
      return new bcgov.rsbc.ride.kafka.evteventproducer.model.payment.columnValues.Builder(other);
    }
  }

  /**
   * RecordBuilder for columnValues instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<columnValues>
    implements org.apache.avro.data.RecordBuilder<columnValues> {

    private java.lang.String personId;
    private java.lang.String email;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(bcgov.rsbc.ride.kafka.evteventproducer.model.payment.columnValues.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.personId)) {
        this.personId = data().deepCopy(fields()[0].schema(), other.personId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.email)) {
        this.email = data().deepCopy(fields()[1].schema(), other.email);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing columnValues instance
     * @param other The existing instance to copy.
     */
    private Builder(bcgov.rsbc.ride.kafka.evteventproducer.model.payment.columnValues other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.personId)) {
        this.personId = data().deepCopy(fields()[0].schema(), other.personId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.email)) {
        this.email = data().deepCopy(fields()[1].schema(), other.email);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'personId' field.
      * @return The value.
      */
    public java.lang.String getPersonId() {
      return personId;
    }


    /**
      * Sets the value of the 'personId' field.
      * @param value The value of 'personId'.
      * @return This builder.
      */
    public bcgov.rsbc.ride.kafka.evteventproducer.model.payment.columnValues.Builder setPersonId(java.lang.String value) {
      validate(fields()[0], value);
      this.personId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'personId' field has been set.
      * @return True if the 'personId' field has been set, false otherwise.
      */
    public boolean hasPersonId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'personId' field.
      * @return This builder.
      */
    public bcgov.rsbc.ride.kafka.evteventproducer.model.payment.columnValues.Builder clearPersonId() {
      personId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'email' field.
      * @return The value.
      */
    public java.lang.String getEmail() {
      return email;
    }


    /**
      * Sets the value of the 'email' field.
      * @param value The value of 'email'.
      * @return This builder.
      */
    public bcgov.rsbc.ride.kafka.evteventproducer.model.payment.columnValues.Builder setEmail(java.lang.String value) {
      validate(fields()[1], value);
      this.email = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'email' field has been set.
      * @return True if the 'email' field has been set, false otherwise.
      */
    public boolean hasEmail() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'email' field.
      * @return This builder.
      */
    public bcgov.rsbc.ride.kafka.evteventproducer.model.payment.columnValues.Builder clearEmail() {
      email = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public columnValues build() {
      try {
        columnValues record = new columnValues();
        record.personId = fieldSetFlags()[0] ? this.personId : (java.lang.String) defaultValue(fields()[0]);
        record.email = fieldSetFlags()[1] ? this.email : (java.lang.String) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<columnValues>
    WRITER$ = (org.apache.avro.io.DatumWriter<columnValues>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<columnValues>
    READER$ = (org.apache.avro.io.DatumReader<columnValues>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.personId);

    out.writeString(this.email);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.personId = in.readString();

      this.email = in.readString();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.personId = in.readString();
          break;

        case 1:
          this.email = in.readString();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










