/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package bcgov.rsbc.ride.kafka.evteventproducer.model.payment;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class EVT_Payment_Event extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -2388081638265658262L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"EVT_Payment_Event\",\"namespace\":\"bcgov.rsbc.ride.kafka.evteventproducer.model.payment\",\"fields\":[{\"name\":\"ticket_no\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"\"},{\"name\":\"count_nbr\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"\"},{\"name\":\"transaction_id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"\"},{\"name\":\"payment_card_type_txt\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"\"},{\"name\":\"payment_ticket_type_cd\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"\"},{\"name\":\"payment_amt\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"\"},{\"name\":\"receipt_nbr\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<EVT_Payment_Event> ENCODER =
      new BinaryMessageEncoder<EVT_Payment_Event>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<EVT_Payment_Event> DECODER =
      new BinaryMessageDecoder<EVT_Payment_Event>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<EVT_Payment_Event> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<EVT_Payment_Event> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<EVT_Payment_Event> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<EVT_Payment_Event>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this EVT_Payment_Event to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a EVT_Payment_Event from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a EVT_Payment_Event instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static EVT_Payment_Event fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.String ticket_no;
  @Deprecated public java.lang.String count_nbr;
  @Deprecated public java.lang.String transaction_id;
  @Deprecated public java.lang.String payment_card_type_txt;
  @Deprecated public java.lang.String payment_ticket_type_cd;
  @Deprecated public java.lang.String payment_amt;
  @Deprecated public java.lang.String receipt_nbr;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public EVT_Payment_Event() {}

  /**
   * All-args constructor.
   * @param ticket_no The new value for ticket_no
   * @param count_nbr The new value for count_nbr
   * @param transaction_id The new value for transaction_id
   * @param payment_card_type_txt The new value for payment_card_type_txt
   * @param payment_ticket_type_cd The new value for payment_ticket_type_cd
   * @param payment_amt The new value for payment_amt
   * @param receipt_nbr The new value for receipt_nbr
   */
  public EVT_Payment_Event(java.lang.String ticket_no, java.lang.String count_nbr, java.lang.String transaction_id, java.lang.String payment_card_type_txt, java.lang.String payment_ticket_type_cd, java.lang.String payment_amt, java.lang.String receipt_nbr) {
    this.ticket_no = ticket_no;
    this.count_nbr = count_nbr;
    this.transaction_id = transaction_id;
    this.payment_card_type_txt = payment_card_type_txt;
    this.payment_ticket_type_cd = payment_ticket_type_cd;
    this.payment_amt = payment_amt;
    this.receipt_nbr = receipt_nbr;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return ticket_no;
    case 1: return count_nbr;
    case 2: return transaction_id;
    case 3: return payment_card_type_txt;
    case 4: return payment_ticket_type_cd;
    case 5: return payment_amt;
    case 6: return receipt_nbr;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: ticket_no = value$ != null ? value$.toString() : null; break;
    case 1: count_nbr = value$ != null ? value$.toString() : null; break;
    case 2: transaction_id = value$ != null ? value$.toString() : null; break;
    case 3: payment_card_type_txt = value$ != null ? value$.toString() : null; break;
    case 4: payment_ticket_type_cd = value$ != null ? value$.toString() : null; break;
    case 5: payment_amt = value$ != null ? value$.toString() : null; break;
    case 6: receipt_nbr = value$ != null ? value$.toString() : null; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'ticket_no' field.
   * @return The value of the 'ticket_no' field.
   */
  public java.lang.String getTicketNo() {
    return ticket_no;
  }


  /**
   * Sets the value of the 'ticket_no' field.
   * @param value the value to set.
   */
  public void setTicketNo(java.lang.String value) {
    this.ticket_no = value;
  }

  /**
   * Gets the value of the 'count_nbr' field.
   * @return The value of the 'count_nbr' field.
   */
  public java.lang.String getCountNbr() {
    return count_nbr;
  }


  /**
   * Sets the value of the 'count_nbr' field.
   * @param value the value to set.
   */
  public void setCountNbr(java.lang.String value) {
    this.count_nbr = value;
  }

  /**
   * Gets the value of the 'transaction_id' field.
   * @return The value of the 'transaction_id' field.
   */
  public java.lang.String getTransactionId() {
    return transaction_id;
  }


  /**
   * Sets the value of the 'transaction_id' field.
   * @param value the value to set.
   */
  public void setTransactionId(java.lang.String value) {
    this.transaction_id = value;
  }

  /**
   * Gets the value of the 'payment_card_type_txt' field.
   * @return The value of the 'payment_card_type_txt' field.
   */
  public java.lang.String getPaymentCardTypeTxt() {
    return payment_card_type_txt;
  }


  /**
   * Sets the value of the 'payment_card_type_txt' field.
   * @param value the value to set.
   */
  public void setPaymentCardTypeTxt(java.lang.String value) {
    this.payment_card_type_txt = value;
  }

  /**
   * Gets the value of the 'payment_ticket_type_cd' field.
   * @return The value of the 'payment_ticket_type_cd' field.
   */
  public java.lang.String getPaymentTicketTypeCd() {
    return payment_ticket_type_cd;
  }


  /**
   * Sets the value of the 'payment_ticket_type_cd' field.
   * @param value the value to set.
   */
  public void setPaymentTicketTypeCd(java.lang.String value) {
    this.payment_ticket_type_cd = value;
  }

  /**
   * Gets the value of the 'payment_amt' field.
   * @return The value of the 'payment_amt' field.
   */
  public java.lang.String getPaymentAmt() {
    return payment_amt;
  }


  /**
   * Sets the value of the 'payment_amt' field.
   * @param value the value to set.
   */
  public void setPaymentAmt(java.lang.String value) {
    this.payment_amt = value;
  }

  /**
   * Gets the value of the 'receipt_nbr' field.
   * @return The value of the 'receipt_nbr' field.
   */
  public java.lang.String getReceiptNbr() {
    return receipt_nbr;
  }


  /**
   * Sets the value of the 'receipt_nbr' field.
   * @param value the value to set.
   */
  public void setReceiptNbr(java.lang.String value) {
    this.receipt_nbr = value;
  }

  /**
   * Creates a new EVT_Payment_Event RecordBuilder.
   * @return A new EVT_Payment_Event RecordBuilder
   */
  public static bcgov.rsbc.ride.kafka.evteventproducer.model.payment.EVT_Payment_Event.Builder newBuilder() {
    return new bcgov.rsbc.ride.kafka.evteventproducer.model.payment.EVT_Payment_Event.Builder();
  }

  /**
   * Creates a new EVT_Payment_Event RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new EVT_Payment_Event RecordBuilder
   */
  public static bcgov.rsbc.ride.kafka.evteventproducer.model.payment.EVT_Payment_Event.Builder newBuilder(bcgov.rsbc.ride.kafka.evteventproducer.model.payment.EVT_Payment_Event.Builder other) {
    if (other == null) {
      return new bcgov.rsbc.ride.kafka.evteventproducer.model.payment.EVT_Payment_Event.Builder();
    } else {
      return new bcgov.rsbc.ride.kafka.evteventproducer.model.payment.EVT_Payment_Event.Builder(other);
    }
  }

  /**
   * Creates a new EVT_Payment_Event RecordBuilder by copying an existing EVT_Payment_Event instance.
   * @param other The existing instance to copy.
   * @return A new EVT_Payment_Event RecordBuilder
   */
  public static bcgov.rsbc.ride.kafka.evteventproducer.model.payment.EVT_Payment_Event.Builder newBuilder(bcgov.rsbc.ride.kafka.evteventproducer.model.payment.EVT_Payment_Event other) {
    if (other == null) {
      return new bcgov.rsbc.ride.kafka.evteventproducer.model.payment.EVT_Payment_Event.Builder();
    } else {
      return new bcgov.rsbc.ride.kafka.evteventproducer.model.payment.EVT_Payment_Event.Builder(other);
    }
  }

  /**
   * RecordBuilder for EVT_Payment_Event instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<EVT_Payment_Event>
    implements org.apache.avro.data.RecordBuilder<EVT_Payment_Event> {

    private java.lang.String ticket_no;
    private java.lang.String count_nbr;
    private java.lang.String transaction_id;
    private java.lang.String payment_card_type_txt;
    private java.lang.String payment_ticket_type_cd;
    private java.lang.String payment_amt;
    private java.lang.String receipt_nbr;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(bcgov.rsbc.ride.kafka.evteventproducer.model.payment.EVT_Payment_Event.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.ticket_no)) {
        this.ticket_no = data().deepCopy(fields()[0].schema(), other.ticket_no);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.count_nbr)) {
        this.count_nbr = data().deepCopy(fields()[1].schema(), other.count_nbr);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.transaction_id)) {
        this.transaction_id = data().deepCopy(fields()[2].schema(), other.transaction_id);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.payment_card_type_txt)) {
        this.payment_card_type_txt = data().deepCopy(fields()[3].schema(), other.payment_card_type_txt);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.payment_ticket_type_cd)) {
        this.payment_ticket_type_cd = data().deepCopy(fields()[4].schema(), other.payment_ticket_type_cd);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.payment_amt)) {
        this.payment_amt = data().deepCopy(fields()[5].schema(), other.payment_amt);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.receipt_nbr)) {
        this.receipt_nbr = data().deepCopy(fields()[6].schema(), other.receipt_nbr);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
    }

    /**
     * Creates a Builder by copying an existing EVT_Payment_Event instance
     * @param other The existing instance to copy.
     */
    private Builder(bcgov.rsbc.ride.kafka.evteventproducer.model.payment.EVT_Payment_Event other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.ticket_no)) {
        this.ticket_no = data().deepCopy(fields()[0].schema(), other.ticket_no);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.count_nbr)) {
        this.count_nbr = data().deepCopy(fields()[1].schema(), other.count_nbr);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.transaction_id)) {
        this.transaction_id = data().deepCopy(fields()[2].schema(), other.transaction_id);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.payment_card_type_txt)) {
        this.payment_card_type_txt = data().deepCopy(fields()[3].schema(), other.payment_card_type_txt);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.payment_ticket_type_cd)) {
        this.payment_ticket_type_cd = data().deepCopy(fields()[4].schema(), other.payment_ticket_type_cd);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.payment_amt)) {
        this.payment_amt = data().deepCopy(fields()[5].schema(), other.payment_amt);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.receipt_nbr)) {
        this.receipt_nbr = data().deepCopy(fields()[6].schema(), other.receipt_nbr);
        fieldSetFlags()[6] = true;
      }
    }

    /**
      * Gets the value of the 'ticket_no' field.
      * @return The value.
      */
    public java.lang.String getTicketNo() {
      return ticket_no;
    }


    /**
      * Sets the value of the 'ticket_no' field.
      * @param value The value of 'ticket_no'.
      * @return This builder.
      */
    public bcgov.rsbc.ride.kafka.evteventproducer.model.payment.EVT_Payment_Event.Builder setTicketNo(java.lang.String value) {
      validate(fields()[0], value);
      this.ticket_no = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'ticket_no' field has been set.
      * @return True if the 'ticket_no' field has been set, false otherwise.
      */
    public boolean hasTicketNo() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'ticket_no' field.
      * @return This builder.
      */
    public bcgov.rsbc.ride.kafka.evteventproducer.model.payment.EVT_Payment_Event.Builder clearTicketNo() {
      ticket_no = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'count_nbr' field.
      * @return The value.
      */
    public java.lang.String getCountNbr() {
      return count_nbr;
    }


    /**
      * Sets the value of the 'count_nbr' field.
      * @param value The value of 'count_nbr'.
      * @return This builder.
      */
    public bcgov.rsbc.ride.kafka.evteventproducer.model.payment.EVT_Payment_Event.Builder setCountNbr(java.lang.String value) {
      validate(fields()[1], value);
      this.count_nbr = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'count_nbr' field has been set.
      * @return True if the 'count_nbr' field has been set, false otherwise.
      */
    public boolean hasCountNbr() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'count_nbr' field.
      * @return This builder.
      */
    public bcgov.rsbc.ride.kafka.evteventproducer.model.payment.EVT_Payment_Event.Builder clearCountNbr() {
      count_nbr = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'transaction_id' field.
      * @return The value.
      */
    public java.lang.String getTransactionId() {
      return transaction_id;
    }


    /**
      * Sets the value of the 'transaction_id' field.
      * @param value The value of 'transaction_id'.
      * @return This builder.
      */
    public bcgov.rsbc.ride.kafka.evteventproducer.model.payment.EVT_Payment_Event.Builder setTransactionId(java.lang.String value) {
      validate(fields()[2], value);
      this.transaction_id = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'transaction_id' field has been set.
      * @return True if the 'transaction_id' field has been set, false otherwise.
      */
    public boolean hasTransactionId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'transaction_id' field.
      * @return This builder.
      */
    public bcgov.rsbc.ride.kafka.evteventproducer.model.payment.EVT_Payment_Event.Builder clearTransactionId() {
      transaction_id = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'payment_card_type_txt' field.
      * @return The value.
      */
    public java.lang.String getPaymentCardTypeTxt() {
      return payment_card_type_txt;
    }


    /**
      * Sets the value of the 'payment_card_type_txt' field.
      * @param value The value of 'payment_card_type_txt'.
      * @return This builder.
      */
    public bcgov.rsbc.ride.kafka.evteventproducer.model.payment.EVT_Payment_Event.Builder setPaymentCardTypeTxt(java.lang.String value) {
      validate(fields()[3], value);
      this.payment_card_type_txt = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'payment_card_type_txt' field has been set.
      * @return True if the 'payment_card_type_txt' field has been set, false otherwise.
      */
    public boolean hasPaymentCardTypeTxt() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'payment_card_type_txt' field.
      * @return This builder.
      */
    public bcgov.rsbc.ride.kafka.evteventproducer.model.payment.EVT_Payment_Event.Builder clearPaymentCardTypeTxt() {
      payment_card_type_txt = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'payment_ticket_type_cd' field.
      * @return The value.
      */
    public java.lang.String getPaymentTicketTypeCd() {
      return payment_ticket_type_cd;
    }


    /**
      * Sets the value of the 'payment_ticket_type_cd' field.
      * @param value The value of 'payment_ticket_type_cd'.
      * @return This builder.
      */
    public bcgov.rsbc.ride.kafka.evteventproducer.model.payment.EVT_Payment_Event.Builder setPaymentTicketTypeCd(java.lang.String value) {
      validate(fields()[4], value);
      this.payment_ticket_type_cd = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'payment_ticket_type_cd' field has been set.
      * @return True if the 'payment_ticket_type_cd' field has been set, false otherwise.
      */
    public boolean hasPaymentTicketTypeCd() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'payment_ticket_type_cd' field.
      * @return This builder.
      */
    public bcgov.rsbc.ride.kafka.evteventproducer.model.payment.EVT_Payment_Event.Builder clearPaymentTicketTypeCd() {
      payment_ticket_type_cd = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'payment_amt' field.
      * @return The value.
      */
    public java.lang.String getPaymentAmt() {
      return payment_amt;
    }


    /**
      * Sets the value of the 'payment_amt' field.
      * @param value The value of 'payment_amt'.
      * @return This builder.
      */
    public bcgov.rsbc.ride.kafka.evteventproducer.model.payment.EVT_Payment_Event.Builder setPaymentAmt(java.lang.String value) {
      validate(fields()[5], value);
      this.payment_amt = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'payment_amt' field has been set.
      * @return True if the 'payment_amt' field has been set, false otherwise.
      */
    public boolean hasPaymentAmt() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'payment_amt' field.
      * @return This builder.
      */
    public bcgov.rsbc.ride.kafka.evteventproducer.model.payment.EVT_Payment_Event.Builder clearPaymentAmt() {
      payment_amt = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'receipt_nbr' field.
      * @return The value.
      */
    public java.lang.String getReceiptNbr() {
      return receipt_nbr;
    }


    /**
      * Sets the value of the 'receipt_nbr' field.
      * @param value The value of 'receipt_nbr'.
      * @return This builder.
      */
    public bcgov.rsbc.ride.kafka.evteventproducer.model.payment.EVT_Payment_Event.Builder setReceiptNbr(java.lang.String value) {
      validate(fields()[6], value);
      this.receipt_nbr = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'receipt_nbr' field has been set.
      * @return True if the 'receipt_nbr' field has been set, false otherwise.
      */
    public boolean hasReceiptNbr() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'receipt_nbr' field.
      * @return This builder.
      */
    public bcgov.rsbc.ride.kafka.evteventproducer.model.payment.EVT_Payment_Event.Builder clearReceiptNbr() {
      receipt_nbr = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public EVT_Payment_Event build() {
      try {
        EVT_Payment_Event record = new EVT_Payment_Event();
        record.ticket_no = fieldSetFlags()[0] ? this.ticket_no : (java.lang.String) defaultValue(fields()[0]);
        record.count_nbr = fieldSetFlags()[1] ? this.count_nbr : (java.lang.String) defaultValue(fields()[1]);
        record.transaction_id = fieldSetFlags()[2] ? this.transaction_id : (java.lang.String) defaultValue(fields()[2]);
        record.payment_card_type_txt = fieldSetFlags()[3] ? this.payment_card_type_txt : (java.lang.String) defaultValue(fields()[3]);
        record.payment_ticket_type_cd = fieldSetFlags()[4] ? this.payment_ticket_type_cd : (java.lang.String) defaultValue(fields()[4]);
        record.payment_amt = fieldSetFlags()[5] ? this.payment_amt : (java.lang.String) defaultValue(fields()[5]);
        record.receipt_nbr = fieldSetFlags()[6] ? this.receipt_nbr : (java.lang.String) defaultValue(fields()[6]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<EVT_Payment_Event>
    WRITER$ = (org.apache.avro.io.DatumWriter<EVT_Payment_Event>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<EVT_Payment_Event>
    READER$ = (org.apache.avro.io.DatumReader<EVT_Payment_Event>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.ticket_no);

    out.writeString(this.count_nbr);

    out.writeString(this.transaction_id);

    out.writeString(this.payment_card_type_txt);

    out.writeString(this.payment_ticket_type_cd);

    out.writeString(this.payment_amt);

    out.writeString(this.receipt_nbr);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.ticket_no = in.readString();

      this.count_nbr = in.readString();

      this.transaction_id = in.readString();

      this.payment_card_type_txt = in.readString();

      this.payment_ticket_type_cd = in.readString();

      this.payment_amt = in.readString();

      this.receipt_nbr = in.readString();

    } else {
      for (int i = 0; i < 7; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.ticket_no = in.readString();
          break;

        case 1:
          this.count_nbr = in.readString();
          break;

        case 2:
          this.transaction_id = in.readString();
          break;

        case 3:
          this.payment_card_type_txt = in.readString();
          break;

        case 4:
          this.payment_ticket_type_cd = in.readString();
          break;

        case 5:
          this.payment_amt = in.readString();
          break;

        case 6:
          this.receipt_nbr = in.readString();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










