/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package bcgov.rsbc.ride.kafka.evteventproducer.model.payment;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class payment_event extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6324168396572552210L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"payment_event\",\"namespace\":\"bcgov.rsbc.ride.kafka.evteventproducer.model.payment\",\"fields\":[{\"name\":\"columns\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"columnValues\",\"fields\":[{\"name\":\"personId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"default\":\"null\"},{\"name\":\"email\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"default\":\"null\"}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<payment_event> ENCODER =
      new BinaryMessageEncoder<payment_event>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<payment_event> DECODER =
      new BinaryMessageDecoder<payment_event>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<payment_event> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<payment_event> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<payment_event> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<payment_event>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this payment_event to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a payment_event from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a payment_event instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static payment_event fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.util.List<bcgov.rsbc.ride.kafka.evteventproducer.model.payment.columnValues> columns;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public payment_event() {}

  /**
   * All-args constructor.
   * @param columns The new value for columns
   */
  public payment_event(java.util.List<bcgov.rsbc.ride.kafka.evteventproducer.model.payment.columnValues> columns) {
    this.columns = columns;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return columns;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: columns = (java.util.List<bcgov.rsbc.ride.kafka.evteventproducer.model.payment.columnValues>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'columns' field.
   * @return The value of the 'columns' field.
   */
  public java.util.List<bcgov.rsbc.ride.kafka.evteventproducer.model.payment.columnValues> getColumns() {
    return columns;
  }


  /**
   * Sets the value of the 'columns' field.
   * @param value the value to set.
   */
  public void setColumns(java.util.List<bcgov.rsbc.ride.kafka.evteventproducer.model.payment.columnValues> value) {
    this.columns = value;
  }

  /**
   * Creates a new payment_event RecordBuilder.
   * @return A new payment_event RecordBuilder
   */
  public static bcgov.rsbc.ride.kafka.evteventproducer.model.payment.payment_event.Builder newBuilder() {
    return new bcgov.rsbc.ride.kafka.evteventproducer.model.payment.payment_event.Builder();
  }

  /**
   * Creates a new payment_event RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new payment_event RecordBuilder
   */
  public static bcgov.rsbc.ride.kafka.evteventproducer.model.payment.payment_event.Builder newBuilder(bcgov.rsbc.ride.kafka.evteventproducer.model.payment.payment_event.Builder other) {
    if (other == null) {
      return new bcgov.rsbc.ride.kafka.evteventproducer.model.payment.payment_event.Builder();
    } else {
      return new bcgov.rsbc.ride.kafka.evteventproducer.model.payment.payment_event.Builder(other);
    }
  }

  /**
   * Creates a new payment_event RecordBuilder by copying an existing payment_event instance.
   * @param other The existing instance to copy.
   * @return A new payment_event RecordBuilder
   */
  public static bcgov.rsbc.ride.kafka.evteventproducer.model.payment.payment_event.Builder newBuilder(bcgov.rsbc.ride.kafka.evteventproducer.model.payment.payment_event other) {
    if (other == null) {
      return new bcgov.rsbc.ride.kafka.evteventproducer.model.payment.payment_event.Builder();
    } else {
      return new bcgov.rsbc.ride.kafka.evteventproducer.model.payment.payment_event.Builder(other);
    }
  }

  /**
   * RecordBuilder for payment_event instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<payment_event>
    implements org.apache.avro.data.RecordBuilder<payment_event> {

    private java.util.List<bcgov.rsbc.ride.kafka.evteventproducer.model.payment.columnValues> columns;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(bcgov.rsbc.ride.kafka.evteventproducer.model.payment.payment_event.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.columns)) {
        this.columns = data().deepCopy(fields()[0].schema(), other.columns);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing payment_event instance
     * @param other The existing instance to copy.
     */
    private Builder(bcgov.rsbc.ride.kafka.evteventproducer.model.payment.payment_event other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.columns)) {
        this.columns = data().deepCopy(fields()[0].schema(), other.columns);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'columns' field.
      * @return The value.
      */
    public java.util.List<bcgov.rsbc.ride.kafka.evteventproducer.model.payment.columnValues> getColumns() {
      return columns;
    }


    /**
      * Sets the value of the 'columns' field.
      * @param value The value of 'columns'.
      * @return This builder.
      */
    public bcgov.rsbc.ride.kafka.evteventproducer.model.payment.payment_event.Builder setColumns(java.util.List<bcgov.rsbc.ride.kafka.evteventproducer.model.payment.columnValues> value) {
      validate(fields()[0], value);
      this.columns = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'columns' field has been set.
      * @return True if the 'columns' field has been set, false otherwise.
      */
    public boolean hasColumns() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'columns' field.
      * @return This builder.
      */
    public bcgov.rsbc.ride.kafka.evteventproducer.model.payment.payment_event.Builder clearColumns() {
      columns = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public payment_event build() {
      try {
        payment_event record = new payment_event();
        record.columns = fieldSetFlags()[0] ? this.columns : (java.util.List<bcgov.rsbc.ride.kafka.evteventproducer.model.payment.columnValues>) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<payment_event>
    WRITER$ = (org.apache.avro.io.DatumWriter<payment_event>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<payment_event>
    READER$ = (org.apache.avro.io.DatumReader<payment_event>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    long size0 = this.columns.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (bcgov.rsbc.ride.kafka.evteventproducer.model.payment.columnValues e0: this.columns) {
      actualSize0++;
      out.startItem();
      e0.customEncode(out);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      long size0 = in.readArrayStart();
      java.util.List<bcgov.rsbc.ride.kafka.evteventproducer.model.payment.columnValues> a0 = this.columns;
      if (a0 == null) {
        a0 = new SpecificData.Array<bcgov.rsbc.ride.kafka.evteventproducer.model.payment.columnValues>((int)size0, SCHEMA$.getField("columns").schema());
        this.columns = a0;
      } else a0.clear();
      SpecificData.Array<bcgov.rsbc.ride.kafka.evteventproducer.model.payment.columnValues> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<bcgov.rsbc.ride.kafka.evteventproducer.model.payment.columnValues>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          bcgov.rsbc.ride.kafka.evteventproducer.model.payment.columnValues e0 = (ga0 != null ? ga0.peek() : null);
          if (e0 == null) {
            e0 = new bcgov.rsbc.ride.kafka.evteventproducer.model.payment.columnValues();
          }
          e0.customDecode(in);
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          long size0 = in.readArrayStart();
          java.util.List<bcgov.rsbc.ride.kafka.evteventproducer.model.payment.columnValues> a0 = this.columns;
          if (a0 == null) {
            a0 = new SpecificData.Array<bcgov.rsbc.ride.kafka.evteventproducer.model.payment.columnValues>((int)size0, SCHEMA$.getField("columns").schema());
            this.columns = a0;
          } else a0.clear();
          SpecificData.Array<bcgov.rsbc.ride.kafka.evteventproducer.model.payment.columnValues> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<bcgov.rsbc.ride.kafka.evteventproducer.model.payment.columnValues>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              bcgov.rsbc.ride.kafka.evteventproducer.model.payment.columnValues e0 = (ga0 != null ? ga0.peek() : null);
              if (e0 == null) {
                e0 = new bcgov.rsbc.ride.kafka.evteventproducer.model.payment.columnValues();
              }
              e0.customDecode(in);
              a0.add(e0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










