apiVersion: template.openshift.io/v1
kind: Template
metadata: {}
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      description: Keeps track of changes in the application image
    creationTimestamp: null
    labels:
      shared: "true"
    name: ${NAME}-${COMPONENT}-image
  spec:
    lookupPolicy:
      local: false
    tags: []
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations: {}
    creationTimestamp: null
    labels: {}
    name: ${NAME}-${COMPONENT}${SUFFIX}
  spec:
    completionDeadlineSeconds: 1440
    failedBuildsHistoryLimit: 3
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: ${NAME}-${COMPONENT}-image:${VERSION}
    postCommit: {}
    resources:
      limits:
        cpu: "2"
        memory: 8Gi
      requests:
        cpu: "1"
        memory: 4Gi
    runPolicy: SerialLatestOnly
    source:
      contextDir: ${SOURCE_CONTEXT_DIR}
      type: Binary
    strategy:
      dockerStrategy:
        dockerfilePath: src/main/docker/Dockerfile.multistage
        env: []
      type: Docker
    successfulBuildsHistoryLimit: 3
    triggers:
    - imageChange: {}
      type: ImageChange
    - type: ConfigChange
  status:
    lastVersion: 0
parameters:
- name: NAME
  description: A prefix for all objects
  displayName: Name
  required: true
  value: jh-ride
- name: COMPONENT
  value: kafka-mockconsumer
- name: SUFFIX
  description: A suffix appended to all objects
  displayName: Name Suffix
  required: true
- name: VERSION
  required: true
- name: SOURCE_CONTEXT_DIR
  required: true