name: CI Checks for build

on:
  push:
    branches-ignore:   
      - 'release**'
      - 'main'
      - 'master'
      - 'feature/buildpushpr'
      - 'maincomponent/**'
      - 'feature/producerapi-deployv1'

jobs:
  test_build:
    name: Test the Build
    runs-on: ubuntu-latest
    environment: pr
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3      
      - name: Perform a test build
        run: |
          cd recon-service
          docker build -f Dockerfile-build -t testimage .




