name: CI Checks for monitoring_svc build

on:
  push:
    branches-ignore:   
      - 'release**'
      - 'main'
      - 'master'
      - 'feature/buildpushpr'
      - 'maincomponent/**'
      - 'feature/producerapi-deployv1'

jobs:
  test_build:
    name: Test the Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3    
      - name: Setup
        uses: docker/setup-buildx-action@v2
        with:
          install: true  
      - name: Login
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: ride-monitoring-svc
          file: Dockerfile-build
          push: false


